### PR TITLE
[IndexTable] Fix overflowing sticky column

### LINKED ISSUE #4012: [IndexTable] Sticky column problem with long content
## Issue summary

When the sticky first column of the index table contains content wider than the table container, the table can't be scrolled far enough to see additional content.

108216505-8f1e5300-7100-11eb-99f6-d0c7568d5f6e

## Expected behavior
User should be able to see all the table content after scrolling.

## Actual behavior

User can't see all content of indextable when the first column has long content.

## Reduced test case

_Playground.tsx_
```
import React from 'react';

import {Card, IndexTable, Page, TextStyle, useIndexResourceState} from '../src';

export function Playground() {
  return (
    <Page title="Playground">
      <SimpleIndexTableExample />
      {/* Add the code you want to test in here */}
    </Page>
  );
}

function SimpleIndexTableExample() {
  const customers = [
    {
      id: '3411',
      url: 'customers/341',
      name: 'asdfasdfadsfadsasdfasdfadsfadsasdfasdfadsfadsasdfasdfadsfadsasdfasdfadsfadsasdfasdfadsfadsasdfasdfadsfadsasdfasdfadsfadsasdfasdfadsfadsasdfasdfadsfadsasdfasdfadsfadsasdfasdfadsfadsasdfasdfadsfadsasdfasdfadsfadsasdfasdfadsfadsasdfasdfadsfads',
      location: 'Decatur, USA',
      orders: 20,
      amountSpent: '$2,400',
    },
    {
      id: '2561',
      url: 'customers/256',
      name: 'asdfasdfadsfads asdfasdfadsfads asdfasdfadsfads asdfasdfadsfads asdfasdfadsfads asdfasdfadsfads asdfasdfadsfads asdfasdfadsfads',
      location: 'Los Angeles, USA',
      orders: 30,
      amountSpent: '$140',
    },
  ];
  const resourceName = {
    singular: 'customer',
    plural: 'customers',
  };

  const {
    selectedResources,
    allResourcesSelected,
    handleSelectionChange,
  } = useIndexResourceState(customers);

  const rowMarkup = customers.map(
    ({id, name, location, orders, amountSpent}, index) => (
      <IndexTable.Row
        id={id}
        key={id}
        selected={selectedResources.includes(id)}
        position={index}
      >
        <IndexTable.Cell>
          <TextStyle variation="strong">{name}</TextStyle>
        </IndexTable.Cell>
        <IndexTable.Cell>{location}</IndexTable.Cell>
        <IndexTable.Cell>{orders}</IndexTable.Cell>
        <IndexTable.Cell>{amountSpent}</IndexTable.Cell>
      </IndexTable.Row>
    ),
  );

  return (
    <Card>
      <IndexTable
        resourceName={resourceName}
        itemCount={customers.length}
        selectedItemsCount={
          allResourcesSelected ? 'All' : selectedResources.length
        }
        onSelectionChange={handleSelectionChange}
        headings={[
          {title: 'Name'},
          {title: 'Location'},
          {title: 'Order count'},
          {title: 'Amount spent'},
        ]}
      >
        {rowMarkup}
      </IndexTable>
    </Card>
  );
}

```

## Specifications

```bash
  System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 158.93 MB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
    Yarn: 1.13.0 - ~/.dev/yarn/v1.13.0/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 88.0.4324.182
    Chrome Canary: 90.0.4424.0
    Firefox: 85.0.2
    Firefox Developer Edition: 85.0
    Safari: 13.1.3
  npmPackages:
    react: ^16.9.0 => 16.9.0 
    react-dom: ^16.9.0 => 16.9.0 
```

### PR DESCRIPTION
**Pull request by FCalabria**
### WHY are these changes introduced?

Fixes #4012 

When a table column is sticky and bigger than the container (_aka_, causes an overflow) the table width is not calculated properly and the non-sticky columns overlap the sticky one. Check this [pure html reproduction](https://codesandbox.io/s/icy-river-0srh0k?file=/index.html) for a better understanding of the root issue.

Disclaimer: This PR does not fit the _condensed_ mode of the table, which has it's own issues when overflowing

### WHAT is this pull request doing?

The bug does not happen on small screens because the only sticky column in that size is the one with checkboxes, which is small enough to not cause an issue, but when a sticky column has long texts the problem can happen on bigger screens.

To solve it I calculate dynamically the size of the sticky column(s) and apply the sticky styles only when the full width of the table can fit them without an overflow. If the table is narrower than the sticky columns, the small screen styles are applied (only the checkbox remains sticky)

If users do not want this behaviour, they can still apply a `max-width` and `white-space: wrap` to the wider cells or columns, which is the non-official solution to this bug right now (`web` is doing it, in case you want to check that the fix does not affect that setup)

  <details>
    <summary>Fixed table (gif)</summary>
    Index table with two rows, checkboxes and four more columns. The first column is wider than the table. When scrolling horizontally, only the checkbox remains sticky and the rest of the content scrolls
  </details>

### 🎩 checklist

[Spin instance
](https://admin.web.web-kf1h.paqui-calabria.eu.spin.dev/store/shop1/)
- [ ] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [ ] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [ ] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [ ] Updated the component's `README.md` with documentation changes
- [ ] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

### CODE REVIEW

File: polaris-react/src/components/IndexTable/IndexTable.tsx [hunk 1]
```diff
@@ -279,6 +279,41 @@ function IndexTableBase({
...
+    const lastStickyColumnWidth =
+      lastColumnSticky && lastColumnIsNotTheFirst
+        ? tableHeadings.current[
+            tableHeadings.current.length - 1
+          ].getBoundingClientRect().width
+        : 0;
+    setCanFitStickyColumn(
+      scrollableRect.width >
+        firstStickyColumnWidth + checkboxColumnWidth + lastStickyColumnWidth,
+    );
```
Comment (patrickracicot) [inline polaris-react/src/components/IndexTable/IndexTable.tsx]: (suggestion) Some additional size should be added to the calculation otherwise if the sum of the sizes is 1px bigger, the table will still render, but the UX will seem buggy as no actual content can be seen by the user.

image

**Review by sam-b-rose — APPROVED** [review]
Changes look good! Tested on Storybook and everything appears to be working as expected 💯 

Since you've created a snapshot, could you also add a web spin link with the snapshot version? Just so we can verify the changes in web as well 🙏

**Review by patrickracicot — APPROVED** [review]
LGTM :)
