### PR TITLE
[Listbox] Fix accessibility issues and logic to set active descendant

### LINKED ISSUE #5150: [Listbox] Add support for auto selection
When the Listbox first receives focus and there are no selected options, the first option in the list should be active.
When the Listbox first receives focus and there is a selected option, the first selected option in the list should be active.

The keyboard listeners need to be fixed in the current implementation so that this works for Listbox outside of it being a child of Combobox.

### PR DESCRIPTION
**Pull request by laurkim**
### WHY are these changes introduced?

Resolves #5150.
There have been issues with accessibility on the Listbox component, such as the `aria-activedescendant` not being set when the Listbox is focused until users trigger some initial keyboard interactions (i.e., arrowing down from TextField when TextField is focused).

### WHAT is this pull request doing?

This PR has significant updates to the Listbox in terms of accessibility fixes:
- Automatically sets `aria-activedescendant` to the first option in the Listbox
- Tabs through all the available options and skips through any disabled options when keying up or down
- Loads the next set of options and will get the next viable option from the new set of options If the `onScrollToBottom` prop is passed in
- Does not set an active option when there is no `onScrollToBottom` and all listbox options are disabled
- Updates active option when listbox options are updated (i.e., textfield is focused -> type to filter -> will reset active option based on new list of filtered options)

Because there are so many edge cases for the different flows for `Listbox.Options`, I've split them out into separate demos and playground code below.
    <details>
      <summary>Demo 1: All options enabled and no onScrollToBottom</summary>
      All options enabled and no onScrollToBottom
    </details>
    <details>
      <summary>Demo 2: Every option disabled and no onScrollToBottom</summary>
      Every option disabled and no onScrollToBottom
    </details>
    <details>
      <summary>Demo 3: Every option disabled and onScrollToBottom</summary>
      Every option disabled and onScrollToBottom
    </details>
    <details>
      <summary>Demo 4: Every other option disabled and noScrollToBottom</summary>
      Every other option disabled and noScrollToBottom
    </details>
    <details>
      <summary>Demo 5: Every other option disabled and onScrollToBottom</summary>
      Every other option disabled and onScrollToBottom
    </details>
    <details>
      <summary>Demo 6: Filter through options with every other disabled and no onScrollToBottom</summary>
      Filter through options with every other disabled and no onScrollToBottom
    </details>
    <details>
      <summary>Demo 7: Plain Listbox</summary>
      Listbox not inside a popover
    </details>

## 

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris-react/blob/master/README.md#development)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris-react/blob/master/documentation/Versioning%20and%20changelog.md)

<details>
<summary>Copy-paste this code in <code>playground/Playground.tsx</code> for demo 1</summary>

```jsx
import React, {useState, useCallback, useEffect} from 'react';
import {CirclePlusMinor} from '@shopify/polaris-icons';

import {Page, Combobox, Listbox, TextStyle} from '../src';

const tags = [
  'one',
  'two',
  'three',
  'four',
  'five',
  'six',
  'seven',
  'eight',
  'nine',
  'ten',
  'eleven',
  'twelve',
  'thirteen',
  'fourteen',
  'fifteen',
];

export function Playground() {
  const [inputValue, setInputValue] = useState<string>('');
  const [selectedTags, setSelectedTags] = useState(tags.slice(3, 7));
  const [filteredTags, setFilteredTags] = useState<string[]>(tags.slice(3, 10));

  const handleFilterOptions = useCallback(
    (inputValue: string) => {
      if (inputValue === '') {
        setFilteredTags(selectedTags);
        return;
      }

      const filterRegex = new RegExp(inputValue, 'i');
      const nextFilteredTags = tags.filter((option) =>
        option.match(filterRegex),
      );

      setFilteredTags(nextFilteredTags);
    },
    [selectedTags],
  );

  const handleInputChange = useCallback((value) => {
    setInputValue(value);
  }, []);

  useEffect(() => {
    handleFilterOptions(inputValue);
  }, [inputValue, handleFilterOptions]);

  const handleActiveOptionChange = useCallback((option) => {}, [inputValue]);

  const handleSelect = useCallback(
    (selected) => {
      if (selectedTags.includes(selected)) {
        setSelectedTags(selectedTags.filter((option) => option !== selected));
      } else {
        setSelectedTags([selected, ...selectedTags]);
        handleInputChange('');
      }
    },
    [selectedTags, handleInputChange],
  );

  const formatOption = useCallback(
    (option, disabled) => {
      if (!inputValue) return option;

      const matchIndex = option.toLowerCase().indexOf(inputValue);
      const start = option.slice(0, matchIndex);
      const highlight = option.slice(
        matchIndex,
        matchIndex + inputValue.length,
      );
      const end = option.slice(matchIndex + inputValue.length, option.length);

      return (
        <Listbox.TextOption
          selected={selectedTags.includes(option)}
          disabled={disabled}
        >
          <p>
            {start}
            <TextStyle variation="strong">{highlight}</TextStyle>
            {end}
          </p>
        </Listbox.TextOption>
      );
    },
    [inputValue],
  );

  const input = (
    <Combobox.TextField
      labelHidden
      disabled={false}
      label="Tags"
      value={inputValue}
      type="text"
      autoComplete="on"
      ariaAutocomplete="list"
      onChange={handleInputChange}
    />
  );

  const createActionMarkup = inputValue ? (
    <Listbox.Action
      accessibilityLabel={`Add: ${inputValue}`}
      value={inputValue}
      icon={CirclePlusMinor}
    >
      <p>
        <TextStyle variation="strong">Add: </TextStyle>
        {inputValue}
      </p>
    </Listbox.Action>
  ) : null;

  const optionMarkup =
    filteredTags.length > 0
      ? filteredTags.map((option) => {
          const disabled = false;
          return (
            <Listbox.Option
              key={option}
              value={option}
              selected={selectedTags.includes(option)}
              disabled={disabled}
            >
              {formatOption(option, disabled)}
            </Listbox.Option>
          );
        })
      : null;

  const listboxMarkup =
    optionMarkup || createActionMarkup ? (
      <Listbox
        accessibilityLabel="Find or create tags"
        onSelect={handleSelect}
        onActiveOptionChange={handleActiveOptionChange}
        enableKeyboardControl
      >
        {optionMarkup}
        {createActionMarkup}
      </Listbox>
    ) : null;

  return (
    <Page title="Playground">
      <Combobox
        activator={input}
        allowMultiple
      >
        {listboxMarkup}
      </Combobox>
    </Page>
  );
}
```

</details>

<details>
<summary>Copy-paste this code in <code>playground/Playground.tsx</code> for demo 2</summary>

```jsx
import React, {useState, useCallback, useEffect} from 'react';
import {CirclePlusMinor} from '@shopify/polaris-icons';

import {Page, Combobox, Listbox, TextStyle} from '../src';

const tags = [
  'one',
  'two',
  'three',
  'four',
  'five',
  'six',
  'seven',
  'eight',
  'nine',
  'ten',
  'eleven',
  'twelve',
  'thirteen',
  'fourteen',
  'fifteen',
];

export function Playground() {
  const [inputValue, setInputValue] = useState<string>('');
  const [selectedTags, setSelectedTags] = useState(tags.slice(3, 7));
  const [filteredTags, setFilteredTags] = useState<string[]>(tags.slice(3, 10));

  const handleFilterOptions = useCallback(
    (inputValue: string) => {
      if (inputValue === '') {
        setFilteredTags(selectedTags);
        return;
      }

      const filterRegex = new RegExp(inputValue, 'i');
      const nextFilteredTags = tags.filter((option) =>
        option.match(filterRegex),
      );

      setFilteredTags(nextFilteredTags);
    },
    [selectedTags],
  );

  const handleInputChange = useCallback((value) => {
    setInputValue(value);
  }, []);

  useEffect(() => {
    handleFilterOptions(inputValue);
  }, [inputValue, handleFilterOptions]);

  const handleActiveOptionChange = useCallback((option) => {}, [inputValue]);

  const handleSelect = useCallback(
    (selected) => {
      if (selectedTags.includes(selected)) {
        setSelectedTags(selectedTags.filter((option) => option !== selected));
      } else {
        setSelectedTags([selected, ...selectedTags]);
        handleInputChange('');
      }
    },
    [selectedTags, handleInputChange],
  );

  const formatOption = useCallback(
    (option, disabled) => {
      if (!inputValue) return option;

      const matchIndex = option.toLowerCase().indexOf(inputValue);
      const start = option.slice(0, matchIndex);
      const highlight = option.slice(
        matchIndex,
        matchIndex + inputValue.length,
      );
      const end = option.slice(matchIndex + inputValue.length, option.length);

      return (
        <Listbox.TextOption
          selected={selectedTags.includes(option)}
          disabled={disabled}
        >
          <p>
            {start}
            <TextStyle variation="strong">{highlight}</TextStyle>
            {end}
          </p>
        </Listbox.TextOption>
      );
    },
    [inputValue],
  );

  const input = (
    <Combobox.TextField
      labelHidden
      disabled={false}
      label="Tags"
      value={inputValue}
      type="text"
      autoComplete="on"
      ariaAutocomplete="list"
      onChange={handleInputChange}
    />
  );

  const createActionMarkup = inputValue ? (
    <Listbox.Action
      accessibilityLabel={`Add: ${inputValue}`}
      value={inputValue}
      icon={CirclePlusMinor}
    >
      <p>
        <TextStyle variation="strong">Add: </TextStyle>
        {inputValue}
      </p>
    </Listbox.Action>
  ) : null;

  const optionMarkup =
    filteredTags.length > 0
      ? filteredTags.map((option, idx) => {
          const disabled = true;
          
          return (
            <Listbox.Option
              key={option}
              value={option}
              selected={selectedTags.includes(option)}
              disabled={disabled}
            >
              {formatOption(option, disabled)}
            </Listbox.Option>
          );
        })
      : null;

  const listboxMarkup =
    optionMarkup || createActionMarkup ? (
      <Listbox
        accessibilityLabel="Find or create tags"
        onSelect={handleSelect}
        onActiveOptionChange={handleActiveOptionChange}
        enableKeyboardControl
      >
        {optionMarkup}
        {createActionMarkup}
      </Listbox>
    ) : null;

  return (
    <Page title="Playground">
      <Combobox activator={input} allowMultiple>
        {listboxMarkup}
      </Combobox>
    </Page>
  );
}
```

</details>

<details>
<summary>Copy-paste this code in <code>playground/Playground.tsx</code> for demo 3</summary>

```jsx
import React, {useState, useCallback, useEffect} from 'react';
import {CirclePlusMinor} from '@shopify/polaris-icons';

import {Page, Combobox, Listbox, TextStyle} from '../src';

const tags = [
  'one',
  'two',
  'three',
  'four',
  'five',
  'six',
  'seven',
  'eight',
  'nine',
  'ten',
  'eleven',
  'twelve',
  'thirteen',
  'fourteen',
  'fifteen',
];

export function Playground() {
  const [inputValue, setInputValue] = useState<string>('');
  const [selectedTags, setSelectedTags] = useState(tags.slice(3, 7));
  const [filteredTags, setFilteredTags] = useState<string[]>(tags.slice(3, 10));

  const handleFilterOptions = useCallback(
    (inputValue: string) => {
      if (inputValue === '') {
        setFilteredTags(selectedTags);
        return;
      }

      const filterRegex = new RegExp(inputValue, 'i');
      const nextFilteredTags = tags.filter((option) =>
        option.match(filterRegex),
      );

      setFilteredTags(nextFilteredTags);
    },
    [selectedTags],
  );

  const handleInputChange = useCallback((value) => {
    setInputValue(value);
  }, []);

  useEffect(() => {
    handleFilterOptions(inputValue);
  }, [inputValue, handleFilterOptions]);

  const handleActiveOptionChange = useCallback((option) => {}, [inputValue]);

  const handleSelect = useCallback(
    (selected) => {
      if (selectedTags.includes(selected)) {
        setSelectedTags(selectedTags.filter((option) => option !== selected));
      } else {
        setSelectedTags([selected, ...selectedTags]);
        handleInputChange('');
      }
    },
    [selectedTags, handleInputChange],
  );

  const formatOption = useCallback(
    (option, disabled) => {
      if (!inputValue) return option;

      const matchIndex = option.toLowerCase().indexOf(inputValue);
      const start = option.slice(0, matchIndex);
      const highlight = option.slice(
        matchIndex,
        matchIndex + inputValue.length,
      );
      const end = option.slice(matchIndex + inputValue.length, option.length);

      return (
        <Listbox.TextOption
          selected={selectedTags.includes(option)}
          disabled={disabled}
        >
          <p>
            {start}
            <TextStyle variation="strong">{highlight}</TextStyle>
            {end}
          </p>
        </Listbox.TextOption>
      );
    },
    [inputValue],
  );

  const input = (
    <Combobox.TextField
      labelHidden
      disabled={false}
      label="Tags"
      value={inputValue}
      type="text"
      autoComplete="on"
      ariaAutocomplete="list"
      onChange={handleInputChange}
    />
  );

  const createActionMarkup = inputValue ? (
    <Listbox.Action
      accessibilityLabel={`Add: ${inputValue}`}
      value={inputValue}
      icon={CirclePlusMinor}
    >
      <p>
        <TextStyle variation="strong">Add: </TextStyle>
        {inputValue}
      </p>
    </Listbox.Action>
  ) : null;

  const optionMarkup =
    filteredTags.length > 0
      ? filteredTags.map((option, idx) => {
          const disabled = idx < 4;
          return (
            <Listbox.Option
              key={option}
              value={option}
              selected={selectedTags.includes(option)}
              disabled={disabled}
            >
              {formatOption(option, disabled)}
            </Listbox.Option>
          );
        })
      : null;

  const listboxMarkup =
    optionMarkup || createActionMarkup ? (
      <Listbox
        accessibilityLabel="Find or create tags"
        onSelect={handleSelect}
        onActiveOptionChange={handleActiveOptionChange}
        enableKeyboardControl
      >
        {optionMarkup}
        {createActionMarkup}
      </Listbox>
    ) : null;

  const handleScrollToBottom = () => {
    setTimeout(() => {
      const newTags = tags.slice(3, 10);
      setSelectedTags(newTags);
    }, 200);
  };

  return (
    <Page title="Playground">
      <Combobox
        activator={input}
        allowMultiple
        onScrolledToBottom={handleScrollToBottom}
      >
        {listboxMarkup}
      </Combobox>
    </Page>
  );
}
```

</details>

<details>
<summary>Copy-paste this code in <code>playground/Playground.tsx</code> for demo 4</summary>

```jsx
import React, {useState, useCallback, useEffect} from 'react';
import {CirclePlusMinor} from '@shopify/polaris-icons';

import {Page, Combobox, Listbox, TextStyle} from '../src';

const tags = [
  'one',
  'two',
  'three',
  'four',
  'five',
  'six',
  'seven',
  'eight',
  'nine',
  'ten',
  'eleven',
  'twelve',
  'thirteen',
  'fourteen',
  'fifteen',
];

export function Playground() {
  const [inputValue, setInputValue] = useState<string>('');
  const [selectedTags, setSelectedTags] = useState(tags.slice(3, 7));
  const [filteredTags, setFilteredTags] = useState<string[]>(tags.slice(3, 10));

  const handleFilterOptions = useCallback(
    (inputValue: string) => {
      if (inputValue === '') {
        setFilteredTags(selectedTags);
        return;
      }

      const filterRegex = new RegExp(inputValue, 'i');
      const nextFilteredTags = tags.filter((option) =>
        option.match(filterRegex),
      );

      setFilteredTags(nextFilteredTags);
    },
    [selectedTags],
  );

  const handleInputChange = useCallback((value) => {
    setInputValue(value);
  }, []);

  useEffect(() => {
    handleFilterOptions(inputValue);
  }, [inputValue, handleFilterOptions]);

  const handleActiveOptionChange = useCallback((option) => {}, [inputValue]);

  const handleSelect = useCallback(
    (selected) => {
      if (selectedTags.includes(selected)) {
        setSelectedTags(selectedTags.filter((option) => option !== selected));
      } else {
        setSelectedTags([selected, ...selectedTags]);
        handleInputChange('');
      }
    },
    [selectedTags, handleInputChange],
  );

  const formatOption = useCallback(
    (option, disabled) => {
      if (!inputValue) return option;

      const matchIndex = option.toLowerCase().indexOf(inputValue);
      const start = option.slice(0, matchIndex);
      const highlight = option.slice(
        matchIndex,
        matchIndex + inputValue.length,
      );
      const end = option.slice(matchIndex + inputValue.length, option.length);

      return (
        <Listbox.TextOption
          selected={selectedTags.includes(option)}
          disabled={disabled}
        >
          <p>
            {start}
            <TextStyle variation="strong">{highlight}</TextStyle>
            {end}
          </p>
        </Listbox.TextOption>
      );
    },
    [inputValue],
  );

  const input = (
    <Combobox.TextField
      labelHidden
      disabled={false}
      label="Tags"
      value={inputValue}
      type="text"
      autoComplete="on"
      ariaAutocomplete="list"
      onChange={handleInputChange}
    />
  );

  const createActionMarkup = inputValue ? (
    <Listbox.Action
      accessibilityLabel={`Add: ${inputValue}`}
      value={inputValue}
      icon={CirclePlusMinor}
    >
      <p>
        <TextStyle variation="strong">Add: </TextStyle>
        {inputValue}
      </p>
    </Listbox.Action>
  ) : null;

  const optionMarkup =
    filteredTags.length > 0
      ? filteredTags.map((option, idx) => {
          const disabled = idx % 2 === 0;
          return (
            <Listbox.Option
              key={option}
              value={option}
              selected={selectedTags.includes(option)}
              disabled={disabled}
            >
              {formatOption(option, disabled)}
            </Listbox.Option>
          );
        })
      : null;

  const listboxMarkup =
    optionMarkup || createActionMarkup ? (
      <Listbox
        accessibilityLabel="Find or create tags"
        onSelect={handleSelect}
        onActiveOptionChange={handleActiveOptionChange}
        enableKeyboardControl
      >
        {optionMarkup}
        {createActionMarkup}
      </Listbox>
    ) : null;

  return (
    <Page title="Playground">
      <Combobox activator={input} allowMultiple>
        {listboxMarkup}
      </Combobox>
    </Page>
  );
}
```

</details>

<details>
<summary>Copy-paste this code in <code>playground/Playground.tsx</code> for demo 5</summary>

```jsx
import React, {useState, useCallback, useEffect} from 'react';
import {CirclePlusMinor} from '@shopify/polaris-icons';

import {Page, Combobox, Listbox, TextStyle} from '../src';

const tags = [
  'one',
  'two',
  'three',
  'four',
  'five',
  'six',
  'seven',
  'eight',
  'nine',
  'ten',
  'eleven',
  'twelve',
  'thirteen',
  'fourteen',
  'fifteen',
];

export function Playground() {
  const [inputValue, setInputValue] = useState<string>('');
  const [selectedTags, setSelectedTags] = useState(tags.slice(3, 7));
  const [filteredTags, setFilteredTags] = useState<string[]>(tags.slice(3, 10));

  const handleFilterOptions = useCallback(
    (inputValue: string) => {
      if (inputValue === '') {
        setFilteredTags(selectedTags);
        return;
      }

      const filterRegex = new RegExp(inputValue, 'i');
      const nextFilteredTags = tags.filter((option) =>
        option.match(filterRegex),
      );

      setFilteredTags(nextFilteredTags);
    },
    [selectedTags],
  );

  const handleInputChange = useCallback((value) => {
    setInputValue(value);
  }, []);

  useEffect(() => {
    handleFilterOptions(inputValue);
  }, [inputValue, handleFilterOptions]);

  const handleActiveOptionChange = useCallback((option) => {}, [inputValue]);

  const handleSelect = useCallback(
    (selected) => {
      if (selectedTags.includes(selected)) {
        setSelectedTags(selectedTags.filter((option) => option !== selected));
      } else {
        setSelectedTags([selected, ...selectedTags]);
        handleInputChange('');
      }
    },
    [selectedTags, handleInputChange],
  );

  const formatOption = useCallback(
    (option, disabled) => {
      if (!inputValue) return option;

      const matchIndex = option.toLowerCase().indexOf(inputValue);
      const start = option.slice(0, matchIndex);
      const highlight = option.slice(
        matchIndex,
        matchIndex + inputValue.length,
      );
      const end = option.slice(matchIndex + inputValue.length, option.length);

      return (
        <Listbox.TextOption
          selected={selectedTags.includes(option)}
          disabled={disabled}
        >
          <p>
            {start}
            <TextStyle variation="strong">{highlight}</TextStyle>
            {end}
          </p>
        </Listbox.TextOption>
      );
    },
    [inputValue],
  );

  const input = (
    <Combobox.TextField
      labelHidden
      disabled={false}
      label="Tags"
      value={inputValue}
      type="text"
      autoComplete="on"
      ariaAutocomplete="list"
      onChange={handleInputChange}
    />
  );

  const createActionMarkup = inputValue ? (
    <Listbox.Action
      accessibilityLabel={`Add: ${inputValue}`}
      value={inputValue}
      icon={CirclePlusMinor}
    >
      <p>
        <TextStyle variation="strong">Add: </TextStyle>
        {inputValue}
      </p>
    </Listbox.Action>
  ) : null;

  const optionMarkup =
    filteredTags.length > 0
      ? filteredTags.map((option, idx) => {
          const disabled = idx % 2 === 0;
          return (
            <Listbox.Option
              key={option}
              value={option}
              selected={selectedTags.includes(option)}
              disabled={disabled}
            >
              {formatOption(option, disabled)}
            </Listbox.Option>
          );
        })
      : null;

  const listboxMarkup =
    optionMarkup || createActionMarkup ? (
      <Listbox
        accessibilityLabel="Find or create tags"
        onSelect={handleSelect}
        onActiveOptionChange={handleActiveOptionChange}
        enableKeyboardControl
      >
        {optionMarkup}
        {createActionMarkup}
      </Listbox>
    ) : null;

  const handleScrollToBottom = () => {
    setTimeout(() => {
      const newTags = tags.slice(3, 9);
      setSelectedTags(newTags);
    }, 200);
  };

  return (
    <Page title="Playground">
      <Combobox
        activator={input}
        allowMultiple
        onScrolledToBottom={handleScrollToBottom}
      >
        {listboxMarkup}
      </Combobox>
    </Page>
  );
}
```

</details>

<details>
<summary>Copy-paste this code in <code>playground/Playground.tsx</code> for demo 6</summary>

```jsx
import React, {useState, useCallback, useEffect} from 'react';
import {CirclePlusMinor} from '@shopify/polaris-icons';

import {Page, Combobox, Listbox, TextStyle} from '../src';

const tags = [
  'one',
  'two',
  'three',
  'four',
  'five',
  'six',
  'seven',
  'eight',
  'nine',
  'ten',
  'eleven',
  'twelve',
  'thirteen',
  'fourteen',
  'fifteen',
];

export function Playground() {
  const [inputValue, setInputValue] = useState<string>('');
  const [selectedTags, setSelectedTags] = useState(tags.slice(3, 7));
  const [filteredTags, setFilteredTags] = useState<string[]>(tags.slice(3, 10));

  const handleFilterOptions = useCallback(
    (inputValue: string) => {
      if (inputValue === '') {
        setFilteredTags(selectedTags);
        return;
      }

      const filterRegex = new RegExp(inputValue, 'i');
      const nextFilteredTags = tags.filter((option) =>
        option.match(filterRegex),
      );

      setFilteredTags(nextFilteredTags);
    },
    [selectedTags],
  );

  const handleInputChange = useCallback((value) => {
    setInputValue(value);
  }, []);

  useEffect(() => {
    handleFilterOptions(inputValue);
  }, [inputValue, handleFilterOptions]);

  const handleActiveOptionChange = useCallback((option) => {}, [inputValue]);

  const handleSelect = useCallback(
    (selected) => {
      if (selectedTags.includes(selected)) {
        setSelectedTags(selectedTags.filter((option) => option !== selected));
      } else {
        setSelectedTags([selected, ...selectedTags]);
        handleInputChange('');
      }
    },
    [selectedTags, handleInputChange],
  );

  const formatOption = useCallback(
    (option, disabled) => {
      if (!inputValue) return option;

      const matchIndex = option.toLowerCase().indexOf(inputValue);
      const start = option.slice(0, matchIndex);
      const highlight = option.slice(
        matchIndex,
        matchIndex + inputValue.length,
      );
      const end = option.slice(matchIndex + inputValue.length, option.length);

      return (
        <Listbox.TextOption
          selected={selectedTags.includes(option)}
          disabled={disabled}
        >
          <p>
            {start}
            <TextStyle variation="strong">{highlight}</TextStyle>
            {end}
          </p>
        </Listbox.TextOption>
      );
    },
    [inputValue],
  );

  const input = (
    <Combobox.TextField
      labelHidden
      disabled={false}
      label="Tags"
      value={inputValue}
      type="text"
      autoComplete="on"
      ariaAutocomplete="list"
      onChange={handleInputChange}
    />
  );

  const createActionMarkup = inputValue ? (
    <Listbox.Action
      accessibilityLabel={`Add: ${inputValue}`}
      value={inputValue}
      icon={CirclePlusMinor}
    >
      <p>
        <TextStyle variation="strong">Add: </TextStyle>
        {inputValue}
      </p>
    </Listbox.Action>
  ) : null;

  const optionMarkup =
    filteredTags.length > 0
      ? filteredTags.map((option, idx) => {
          const disabled = idx % 2 === 0;
          return (
            <Listbox.Option
              key={option}
              value={option}
              selected={selectedTags.includes(option)}
              disabled={disabled}
            >
              {formatOption(option, disabled)}
            </Listbox.Option>
          );
        })
      : null;

  const listboxMarkup =
    optionMarkup || createActionMarkup ? (
      <Listbox
        accessibilityLabel="Find or create tags"
        onSelect={handleSelect}
        onActiveOptionChange={handleActiveOptionChange}
        enableKeyboardControl
      >
        {optionMarkup}
        {createActionMarkup}
      </Listbox>
    ) : null;

  return (
    <Page title="Playground">
      <Combobox activator={input} allowMultiple>
        {listboxMarkup}
      </Combobox>
    </Page>
  );
}
```

</details>

<details>
<summary>Copy-paste this code in <code>playground/Playground.tsx</code> for demo 7</summary>

```jsx
import React from 'react';

import {Page, Listbox} from '../src';

const tags = ['one', 'two', 'three', 'four', 'five', 'six', 'seven'];

export function Playground() {
  const optionMarkup = tags.map((option) => {
    return (
      <Listbox.Option key={option} value={option}>
        <Listbox.TextOption>
          <p>{option}</p>
        </Listbox.TextOption>
      </Listbox.Option>
    );
  });

  const listboxMarkup = (
    <Listbox accessibilityLabel="Find tags" enableKeyboardControl>
      {optionMarkup}
    </Listbox>
  );

  return <Page title="Playground">{listboxMarkup}</Page>;
}
```

</details>

### 🎩 checklist

- [x] Tested on [mobile](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md#cross-browser-testing)
- [x] Tested on [multiple browsers](https://help.shopify.com/en/manual/intro-to-shopify/shopify-admin/supported-browsers)
- [x] Tested for [accessibility](https://github.com/Shopify/polaris-react/blob/master/documentation/Accessibility%20testing.md)
- [ ] Updated the component's `README.md` with documentation changes
- [ ] [Tophatted documentation](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting%20documentation.md) changes in the style guide
- [x] For visual design changes, ping @ sarahill to update the Polaris UI kit

### CODE REVIEW

File: src/components/Listbox/Listbox.tsx [hunk 1]
```diff
@@ -59,45 +62,87 @@ export function Listbox({
...
+    textFieldFocused,
+    setActiveOptionId,
+    setListboxId,
     onOptionSelected,
     onKeyToBottom,
-    textFieldFocused,
   } = useComboboxListbox();
 
   const inCombobox = Boolean(setActiveOptionId);
+  const listboxClassName = classNames(styles.Listbox);
```
Comment (kyledurand) [inline src/components/Listbox/Listbox.tsx]: Looks like we don't need `classNames` here anymore

File: src/components/Listbox/Listbox.tsx [hunk 2]
```diff
@@ -59,45 +62,87 @@ export function Listbox({
...
-    if (!currentActiveOption || !setActiveOptionId) return;
-    setActiveOptionId(currentActiveOption.domId);
-  }, [currentActiveOption, setActiveOptionId]);
+  const getNavigableOptions = () => {
+    if (!listboxRef.current) {
+      return [];
+    }
+
+    return [
+      ...new Set(
```
Comment (kyledurand) [inline src/components/Listbox/Listbox.tsx]: Why does this need to be a set?

File: src/components/Listbox/Listbox.tsx [hunk 3]
```diff
@@ -107,36 +152,116 @@ export function Listbox({
 
         scrollIntoView(focusTarget, scrollableRef.current);
       }
-    }, 15),
+    },
     [],
   );
 
+  const handleScrollIntoViewDebounced = debounce(handleScrollIntoView, 15);
```
Comment (kyledurand) [inline src/components/Listbox/Listbox.tsx]: is 15ms a bit short of a duration here?

File: src/components/Listbox/components/Option/Option.tsx [hunk 4]
```diff
@@ -89,20 +89,21 @@ export const Option = memo(function Option({
...
-      onMouseDown={handleMouseDown}
-      aria-disabled={disabled}
-      onClick={disabled ? undefined : handleOptionClick}
       role={legacyRoleSupport}
       aria-label={accessibilityLabel}
       aria-selected={selected}
-      data-listbox-option
+      aria-disabled={disabled}
+      onClick={disabled ? undefined : handleOptionSelect}
+      onKeyPress={disabled ? undefined : handleOptionSelect}
```
Comment (kyledurand) [inline src/components/Listbox/components/Option/Option.tsx]: Should this be `onKeyUp`? I guess I can't really think of a real difference either way. I just normally use key up

**Review by kyledurand — APPROVED** [review]
Amazing work Lo! This seems like a huge improvement 👏

File: src/components/Listbox/Listbox.tsx (hunk 1 above)
Comment (laurkim) [reply src/components/Listbox/Listbox.tsx]: It doesn't show up in the code diff for this PR but `listboxClassName` is still being used on [line 457](https://github.com/Shopify/polaris-react/blob/91dba7d3faf27ef40efaf16784662216951055cc/src/components/Listbox/Listbox.tsx#L457) after the changes from this PR

File: src/components/Listbox/Listbox.tsx (hunk 2 above)
Comment (laurkim) [reply src/components/Listbox/Listbox.tsx]: This is just reusing some of the original Listbox code when the `Autocomplete` component was originally added last year.
I assume `Set()` was originally used to make sure each option in the Listbox is unique and that there aren't duplicate options

File: src/components/Listbox/Listbox.tsx (hunk 3 above)
Comment (laurkim) [reply src/components/Listbox/Listbox.tsx]: This is the duration originally set when `Autocomplete` was added so I left it as is. 
What duration would you recommend @kyledurand?

File: src/components/Listbox/components/Option/Option.tsx (hunk 4 above)
Comment (laurkim) [reply src/components/Listbox/components/Option/Option.tsx]: Yeah, I'll update it 👍

**Comment by laurkim** [comment]
Latest force push was to resolve conflicts re: folder architecture after monorepo pr was shipped

**Review by chloerice — APPROVED** [review]
🚢 🎉

File: src/components/Listbox/Listbox.tsx (hunk 1 above)
Comment (kyledurand) [reply src/components/Listbox/Listbox.tsx]: Yep but you don't need the `classNames` util anymore since it's just the one class 😄

File: src/components/Listbox/Listbox.tsx (hunk 3 above)
Comment (kyledurand) [reply src/components/Listbox/Listbox.tsx]: All good to leave as is

File: src/components/Listbox/Listbox.tsx (hunk 1 above)
Comment (laurkim) [reply src/components/Listbox/Listbox.tsx]: Oh that was a :whoosh: moment for me haha 😭 
I'll update! 👍
