### PR TITLE
[Popover] fix inappropriate closing issue

### LINKED ISSUE #7097: [Popover] unintentionally closes parent overlays when `onClick` event propogates
## Issue summary

Original issue reported by @nneubarth 

We’re encountering an issue with [`PopoverOverlay` component](https://github.com/Shopify/polaris/blob/main/polaris-react/src/components/Popover/components/PopoverOverlay/PopoverOverlay.tsx) within the Bulk Editor. We have a popover that allows users to delete elements. When a user clicks the delete button, the click event propagates up and is heard by an EventListener within PopoverOverlay , which in turn calls [this ](https://github.com/Shopify/polaris/blob/main/polaris-react/src/components/Popover/components/PopoverOverlay/PopoverOverlay.tsx#L269)handleClick[ function](https://github.com/Shopify/polaris/blob/main/polaris-react/src/components/Popover/components/PopoverOverlay/PopoverOverlay.tsx#L269). Because the original delete button is now absent from the DOM, isDescendant evaluates to false and the popover closes inappropriately. While investigating further we found more cases of inappropriate popover closures after click events. For example, if you click inside a popover that was launched by another popover, both popovers close. The same issue happens if you click inside a modal that was launched by a popover, in which case both the modal and the popover close.

We have a few potential fixes in mind, one inspired by the way the custom CardPopover[ component](https://github.com/Shopify/web/blob/main/app/sections/PriceLists/components/CardPopover/CardPopover.tsx) works. Is this an issue you’re tracking and/or are open to fixing?

## Expected behavior

Overlays should remain open after on click event, even if the activating node is no longer present.

## Actual behavior

In bulk editor

https://user-images.githubusercontent.com/4642404/188237794-9144b026-4b68-41c9-9116-8f7013eab893.mp4

In a modal

https://user-images.githubusercontent.com/4642404/188238254-0cb8005f-4fb7-44be-9f34-0dbeddd1c8fb.mp4

## Reduced test case

[Codesandbox reproduction](https://codesandbox.io/s/divine-platform-t70hjh)

### PR DESCRIPTION
**Pull request by nneubarth**
Spin instance with snapshot changes on `main`: https://shop1.shopify.web-v2vm.nicole-neubarth.us.spin.dev/admin/ (has `deprecate_rails_bulk_editor` and product/variant metafields beta flags enabled)

### WHY are these changes introduced?

Fixes #7097  

There are two issues we're trying to address here: 1) popovers will inappropriately close when a click event removes an element from the DOM, 2) popovers (and their descendants) will inappropriately close when a user clicks inside a descendant portal (another popover, modal, etc).

### WHAT is this pull request doing?

To fix the first issue, we propose using `event.composedPath()` to determine if the event happened inside the popover. This doesn't rely on the `target` of the event existing in the DOM at the time of the check.

To fix the second issue, we propose checking whether the click event happened inside another portal by checking all portals within the `PortalsContainerElement` element, which we can get from `PortalsManagerContext`. This makes the assumption that any other portals on the page are a descendant of the original portal. However, this may not always be the case (e.g. a modal that launches a popover, in which case the modal is a parent of the popover), so we elected to make this an opt-in flag. 

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris/blob/main/README.md#local-development)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md#changelog)

<details>
<summary>Copy-paste this code in <code>playground/Playground.tsx</code>:</summary>

```jsx
import React from 'react';
import {Page} from '../src';

export function Playground() {
  return (
    <Page title="Playground">
      {/* Add the code you want to test in here */}
    </Page>
  );
}
```

</details>

### 🎩 checklist

I’ve tophatted these changes in the following browsers:

- [x] Chrome latest
- [x] FF latest
- [x] Safari latest
- [x] Edge
- [ ] In at least one of the above browsers, test both retina and non-retina displays
- [x] iPhone (5/SE/X) (10+) Safari Mobile
- [x] iPad (10+) Safari Mobile
- [x] Android device (5.x) Chrome

- [x] tophatted in web on `main`
- [x] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

### CODE REVIEW

File: polaris-react/src/components/Popover/components/PopoverOverlay/PopoverOverlay.tsx [hunk 1]
```diff
@@ -333,3 +342,14 @@ export function nodeContainsDescendant(
 
   return false;
 }
+
+function wasPolarisPortalDescendant(
+  composedPath: EventTarget[],
```
Comment (lbenie) [inline polaris-react/src/components/Popover/components/PopoverOverlay/PopoverOverlay.tsx]:
```suggestion
  composedPath: ReadonlyArray<EventTarget>,
```

File: polaris-react/src/components/Popover/components/PopoverOverlay/PopoverOverlay.tsx [hunk 2]
```diff
@@ -52,13 +56,16 @@ export interface PopoverOverlayProps {
...
   autofocusTarget?: PopoverAutofocusTarget;
+  hasPortalDescendants?: boolean;
 }
 
 interface State {
   transitionStatus: TransitionStatus;
 }
 
 export class PopoverOverlay extends PureComponent<PopoverOverlayProps, State> {
+  static contextType = PortalsManagerContext;
```
Comment (lbenie) [inline polaris-react/src/components/Popover/components/PopoverOverlay/PopoverOverlay.tsx:67]: is this needed?

Comment (nneubarth) [reply polaris-react/src/components/Popover/components/PopoverOverlay/PopoverOverlay.tsx:67]: Yes, it's required to listen to the `PortalsManagerContext`, which contains a reference to the portal manager element. https://reactjs.org/docs/context.html#classcontexttype

File: polaris-react/src/components/Popover/components/PopoverOverlay/PopoverOverlay.tsx [hunk 3]
```diff
@@ -270,19 +277,21 @@ export class PopoverOverlay extends PureComponent<PopoverOverlayProps, State> {
...
       contentNode,
-      props: {activator, onClose},
+      props: {activator, onClose, hasPortalDescendants},
     } = this;
-    const isDescendant =
-      contentNode.current != null &&
-      nodeContainsDescendant(contentNode.current, target);
+    const wasDescendant = hasPortalDescendants
+      ? wasPolarisPortalDescendant(event.composedPath(), this.context.container)
+      : contentNode.current != null &&
```
Comment (mattkubej) [inline polaris-react/src/components/Popover/components/PopoverOverlay/PopoverOverlay.tsx]: Might be worth creating a named function for the else condition, so it's obvious what this is intending to validate.

File: polaris-react/src/components/Popover/components/PopoverOverlay/PopoverOverlay.tsx [hunk 4]
```diff
@@ -270,19 +277,21 @@ export class PopoverOverlay extends PureComponent<PopoverOverlayProps, State> {
     const target = event.target as HTMLElement;
     const {
       contentNode,
-      props: {activator, onClose},
+      props: {activator, onClose, hasPortalDescendants},
```
Comment (mattkubej) [inline polaris-react/src/components/Popover/components/PopoverOverlay/PopoverOverlay.tsx]: I'm wondering if we want to come up with a different prop name to describe what we're intending to enable here, so it's obvious from the `<Popover />` interface. I'll need to think about this morning, because I don't have something coming to me that would be succinctly descriptive.

File: polaris-react/src/components/Popover/components/PopoverOverlay/PopoverOverlay.tsx (hunk 3 above)
Comment (nneubarth) [reply polaris-react/src/components/Popover/components/PopoverOverlay/PopoverOverlay.tsx]: Agree

File: polaris-react/src/components/Popover/components/PopoverOverlay/PopoverOverlay.tsx (hunk 4 above)
Comment (nneubarth) [reply polaris-react/src/components/Popover/components/PopoverOverlay/PopoverOverlay.tsx]: switched to `preventCloseOnChildOverlayClick` after discussion with @mattkubej

**Review by lbenie — APPROVED** [review]

**Review by mattkubej — APPROVED** [review]

File: .changeset/tiny-students-burn.md [hunk 5]
```diff
@@ -0,0 +1,5 @@
+---
+'@shopify/polaris': patch
+---
+
+Fixes bug in which deleted elements or clicks inside other portal-based elements were inappropriately closing popovers
```
Comment (kyledurand) [inline .changeset/tiny-students-burn.md]: Can we use past tense here? Start with `Fixed`

File: polaris-react/src/components/Popover/Popover.tsx [hunk 6]
```diff
@@ -76,6 +76,8 @@ export interface PopoverProps {
    * @default 'container'
    */
   autofocusTarget?: PopoverAutofocusTarget;
+  /** Prevents closing the popover when other overlays are clicked */
```
Comment (kyledurand) [inline polaris-react/src/components/Popover/Popover.tsx:79]: Can we be more specific here? From my understanding `other` means nested / child popovers

File: polaris-react/src/components/Popover/components/PopoverOverlay/tests/PopoverOverlay.test.tsx [hunk 7]
```diff
@@ -277,18 +273,116 @@ describe('<PopoverOverlay />', () => {
...
+    expect(spy).not.toHaveBeenCalled();
+  });
+
+  describe('deleting descendant elements', () => {
+    const DeleteButton = () => {
+      const [show, setShow] = React.useState(true);
+
+      return (
+        <>{show && <button onClick={() => setShow(!show)}>Delete</button>}</>
+      );
```
Comment (kyledurand) [inline polaris-react/src/components/Popover/components/PopoverOverlay/tests/PopoverOverlay.test.tsx]:
```suggestion
      return show && <button onClick={() => setShow(!show)}>Delete</button>;
```

File: polaris-react/src/components/Popover/components/PopoverOverlay/tests/PopoverOverlay.test.tsx [hunk 8]
```diff
@@ -277,18 +273,116 @@ describe('<PopoverOverlay />', () => {
...
+          onClose={spy}
+        >
+          <DeleteButton />
+        </PopoverOverlay>,
+      );
+
+      const deleteButton = popoverOverlay.find('button')!.domNode!;
+      const clickEvent = new MouseEvent('click', {bubbles: true});
+
+      deleteButton.dispatchEvent(clickEvent);
```
Comment (kyledurand) [inline polaris-react/src/components/Popover/components/PopoverOverlay/tests/PopoverOverlay.test.tsx:345]:
```suggestion
      popoverOverlay.find('button')!.trigger('onClick', {bubbles: true});
```
I'm not 100% sure this will work as intended but we typically we do something like this vs dispatching events where we can

**Review by kyledurand — APPROVED** [review]
This looks good to me. Just some minor comments around conventions 👍

File: polaris-react/src/components/Popover/Popover.tsx (hunk 6 above)
Comment (nneubarth) [reply polaris-react/src/components/Popover/Popover.tsx:79]: I think `other overlays` is more accurate, but `child overlays` expresses the intended use. The current implementation has no concept of child vs non-child overlays--it assumes _any_ other overlay is a child of the original popover. So I guess is it better to be accurate here or express the intended use?

File: polaris-react/src/components/Popover/components/PopoverOverlay/tests/PopoverOverlay.test.tsx (hunk 8 above)
Comment (nneubarth) [reply polaris-react/src/components/Popover/components/PopoverOverlay/tests/PopoverOverlay.test.tsx:345]: Interesting. I've seen both in `web`. What would be the reason to prefer `trigger` over `dispatchEvent`?

File: polaris-react/src/components/Popover/components/PopoverOverlay/tests/PopoverOverlay.test.tsx (hunk 7 above)
Comment (nneubarth) [reply polaris-react/src/components/Popover/components/PopoverOverlay/tests/PopoverOverlay.test.tsx]: React and the linter won't let me do this. React requires enclosing it in fragment tags, and if I try to one-line that the linter changes it to what I have.

File: polaris-react/src/components/Popover/Popover.tsx (hunk 6 above)
Comment (mattkubej) [reply polaris-react/src/components/Popover/Popover.tsx:79]: The `handleClick` handler isn't strictly enforcing that with this prop on, because I believe all overlays are placed as children of the portal container, so all overlays are siblings. I do not believe we have a mechanism built to discern the parent-child relationship amongst the popovers within Polaris at the moment.

This nearly happens as a side effect of this click handler, because the existing `handleClick` handler will attempt to invoke `onClose` of each popover when they're not being directly interacted with. So, Polaris seems to naturally make the assumption that only one popover will be open at a time and you would not have sibling popovers open simultaneously. This prop allows a parent popover of the children popovers it produces to not have it's `onClose` invoked when its children are being interacted with.

Please correct me if I'm wrong @nneubarth

File: polaris-react/src/components/Popover/components/PopoverOverlay/tests/PopoverOverlay.test.tsx (hunk 8 above)
Comment (kyledurand) [reply polaris-react/src/components/Popover/components/PopoverOverlay/tests/PopoverOverlay.test.tsx:345]: Just more common for click events. Not a blocker but it keeps test suites more consistent. We use dispatch to mock things like window / document listeners more than behavioural interactions

File: polaris-react/src/components/Popover/components/PopoverOverlay/tests/PopoverOverlay.test.tsx (hunk 7 above)
Comment (kyledurand) [reply polaris-react/src/components/Popover/components/PopoverOverlay/tests/PopoverOverlay.test.tsx]: That's because React is trying to render `false` below, so you'll need a ternary:

```suggestion
      return show ? (
        <button onClick={() => setShow(!show)}>Delete</button>
      ) : null;
```

File: polaris-react/src/components/Popover/components/PopoverOverlay/tests/PopoverOverlay.test.tsx (hunk 8 above)
Comment (nneubarth) [reply polaris-react/src/components/Popover/components/PopoverOverlay/tests/PopoverOverlay.test.tsx:345]: I tried to do this and found that invoking `onClick` via `trigger` didn't actually cause the events to bubble the way you expect even when passing `{bubbles:true}`. `trigger` appears to only call the `onClick` prop, so it doesn't test the functionality the way I intend. If you have any other ideas to try let me know, but otherwise I'm going to keep the `dispatchEvent` here because it does mimic the behavior I intend to test.

Comment (kyledurand) [reply polaris-react/src/components/Popover/components/PopoverOverlay/tests/PopoverOverlay.test.tsx:345]: That's strange but all good. Thanks for trying!

File: .changeset/tiny-students-burn.md (hunk 5 above)
Comment (nneubarth) [reply .changeset/tiny-students-burn.md]: Done
