### PR TITLE
[Combobox/Listbox] Fix accessibility issues on focus and option create

### LINKED ISSUE #5148: [Multiselect] Combobox popover closes automatically when adding new option
When selecting an existing option in the listbox, the Combobox popover stays open.
When selecting a new option in the listbox, the Combobox activator stays active but the popover is closed.
This behavior exists in production, when you try to add a new tag in the autocomplete.

Demo gif:
<details>
  <summary>Combobox add existing/new option</summary>
  Combobox add existing/new option
</details>

### PR DESCRIPTION
**Pull request by laurkim**
### WHY are these changes introduced?

Fixes #5148.
First PR to update combobox to unblock work for #5151.
Requires #5297 to be merged first, as this is branched off of that PR. 

### WHAT is this pull request doing?

Fixes bug on Combobox where the popover would close when creating a new option. The base functionality is the same as selecting an existing option but the behaviors were conflicting where, for multiselect, the popover would stay open when selecting an existing option and would close when selecting a new option to create.

Fixes bug on Combobox where active option wasn't being set when the popover is opened.
There were updates for Listbox that were Combobox specific so I've separated it out from the original #5297 PR to minimize complexity.
    <details>
      <summary>Combobox demo - before showing active option not set on focus (requires keydown first)</summary>
      Combobox demo - before showing active option not set on focus (requires keydown first)
    </details>
    <details>
      <summary>Combobox demo - after</summary>
      Combobox demo- after
    </details>

## 

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris-react/blob/master/README.md#development)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris-react/blob/master/documentation/Versioning%20and%20changelog.md)

<details>
<summary>Copy-paste this code in <code>playground/Playground.tsx</code>:</summary>

```jsx
import React, {useState, useCallback, useEffect} from 'react';
import {CirclePlusMinor} from '@shopify/polaris-icons';

import {Page, Combobox, Listbox, TextStyle} from '../src';

const tags = [
  'one',
  'two',
  'three',
  'four',
  'five',
  'six',
  'seven',
  'eight',
  'nine',
  'ten',
  'eleven',
  'twelve',
  'thirteen',
  'fourteen',
  'fifteen',
];

export function Playground() {
  const [inputValue, setInputValue] = useState<string>('');
  const [selectedTags, setSelectedTags] = useState(tags.slice(3, 7));
  const [filteredTags, setFilteredTags] = useState<string[]>(tags.slice(3, 10));

  const handleFilterOptions = useCallback(
    (inputValue: string) => {
      if (inputValue === '') {
        setFilteredTags(selectedTags);
        return;
      }

      const filterRegex = new RegExp(inputValue, 'i');
      const nextFilteredTags = tags.filter((option) =>
        option.match(filterRegex),
      );

      setFilteredTags(nextFilteredTags);
    },
    [selectedTags],
  );

  const handleInputChange = useCallback((value) => {
    setInputValue(value);
  }, []);

  useEffect(() => {
    handleFilterOptions(inputValue);
  }, [inputValue, handleFilterOptions]);

  const handleActiveOptionChange = useCallback((option) => {}, [inputValue]);

  const handleSelect = useCallback(
    (selected) => {
      if (selectedTags.includes(selected)) {
        setSelectedTags(selectedTags.filter((option) => option !== selected));
      } else {
        setSelectedTags([selected, ...selectedTags]);
        handleInputChange('');
      }
    },
    [selectedTags, handleInputChange],
  );

  const formatOption = useCallback(
    (option) => {
      if (!inputValue) return option;

      const matchIndex = option.toLowerCase().indexOf(inputValue);
      const start = option.slice(0, matchIndex);
      const highlight = option.slice(
        matchIndex,
        matchIndex + inputValue.length,
      );
      const end = option.slice(matchIndex + inputValue.length, option.length);

      return (
        <Listbox.TextOption selected={selectedTags.includes(option)}>
          <p>
            {start}
            <TextStyle variation="strong">{highlight}</TextStyle>
            {end}
          </p>
        </Listbox.TextOption>
      );
    },
    [inputValue],
  );

  const input = (
    <Combobox.TextField
      labelHidden
      disabled={false}
      label="Tags"
      value={inputValue}
      type="text"
      autoComplete="on"
      ariaAutocomplete="list"
      onChange={handleInputChange}
    />
  );

  const createActionMarkup = inputValue ? (
    <Listbox.Action
      accessibilityLabel={`Add: ${inputValue}`}
      value={inputValue}
      icon={CirclePlusMinor}
    >
      <p>
        <TextStyle variation="strong">Add: </TextStyle>
        {inputValue}
      </p>
    </Listbox.Action>
  ) : null;

  const optionMarkup =
    filteredTags.length > 0
      ? filteredTags.map((option) => {
          return (
            <Listbox.Option
              key={option}
              value={option}
              selected={selectedTags.includes(option)}
            >
              {formatOption(option)}
            </Listbox.Option>
          );
        })
      : null;

  const listboxMarkup =
    optionMarkup || createActionMarkup ? (
      <Listbox
        accessibilityLabel="Find or create tags"
        onSelect={handleSelect}
        onActiveOptionChange={handleActiveOptionChange}
        enableKeyboardControl
      >
        {optionMarkup}
        {createActionMarkup}
      </Listbox>
    ) : null;

  return (
    <Page title="Playground">
      <Combobox activator={input} allowMultiple>
        {listboxMarkup}
      </Combobox>
    </Page>
  );
}

```

</details>

### 🎩 checklist

- [x] Tested on [mobile](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md#cross-browser-testing)
- [x] Tested on [multiple browsers](https://help.shopify.com/en/manual/intro-to-shopify/shopify-admin/supported-browsers)
- [x] Tested for [accessibility](https://github.com/Shopify/polaris-react/blob/master/documentation/Accessibility%20testing.md)
- [x] Updated the component's `README.md` with documentation changes
- [x] [Tophatted documentation](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting%20documentation.md) changes in the style guide
- [x] For visual design changes, ping @ sarahill to update the Polaris UI kit

### CODE REVIEW

File: polaris-react/src/components/Combobox/Combobox.tsx [hunk 1]
```diff
@@ -17,60 +17,79 @@ import styles from './Combobox.scss';
...
   preferredPosition = 'below',
+  onScrolledToBottom,
 }: ComboboxProps) {
   const [popoverActive, setPopoverActive] = useState(false);
   const [activeOptionId, setActiveOptionId] = useState<string>();
   const [textFieldLabelId, setTextFieldLabelId] = useState<string>();
   const [listboxId, setListboxId] = useState<string>();
   const [textFieldFocused, setTextFieldFocused] = useState<boolean>(false);
+  const [disableCloseOnSelect, setDisableCloseOnSelect] =
+    useState<boolean>(false);
```
Comment (chloerice) [inline polaris-react/src/components/Combobox/Combobox.tsx]:
```suggestion
    useState(false);
```

File: polaris-react/src/components/Combobox/README.md [hunk 2]
```diff
@@ -35,7 +35,7 @@ The input field for `Combobox` should follow the [content guidelines](https://po
 
 ## Examples
 
-### Basic autocomplete
+### Single select autocomplete
```
Comment (chloerice) [inline polaris-react/src/components/Combobox/README.md:38]: ❤️

File: polaris-react/src/components/Combobox/README.md [hunk 3]
```diff
@@ -127,7 +127,7 @@ function ComboboxExample() {
 }
 ```
 
-### Multiple tags autocomplete
+### Multiselect autocomplete
```
Comment (chloerice) [inline polaris-react/src/components/Combobox/README.md]:
```suggestion
### Multi-select autocomplete
```

File: polaris-react/UNRELEASED.md [hunk 4]
```diff
@@ -12,6 +12,7 @@ Use [the changelog guidelines](/documentation/Versioning%20and%20changelog.md) t
 
 ### Bug fixes
 
+- Fixed accessibility issues on focus and option create on `Combobox` and `Listbox` ([#5298](https://github.com/Shopify/polaris-react/pull/5298))
 - Fixed accessibility issues and logic to set active descendant on `Listbox` ([#5297](https://github.com/Shopify/polaris-react/pull/5297))
```
Comment (chloerice) [inline polaris-react/UNRELEASED.md]:
```suggestion
- Fixed accessibility issues on focus and option create in `Combobox` and `Listbox` ([#5298](https://github.com/Shopify/polaris-react/pull/5298))
- Fixed accessibility issues and logic to set active descendant in `Listbox` ([#5297](https://github.com/Shopify/polaris-react/pull/5297))
```

**Review by chloerice — APPROVED** [review]
🙌🏽 🙌🏽 🙌🏽
