### PR TITLE
Button code clean up and bevel fixes

### LINKED ISSUE #11162: Artefacts appearing around primary buttons on hover
## Issue summary

When hovering over many of the primary buttons on web (Chrome, MacOS) strange visual artefacts appear (see below).

Screenshot 2023-11-09 at 8 08 53 AM
Screenshot 2023-11-09 at 8 23 48 AM
Screenshot 2023-11-09 at 8 23 57 AM

## Expected behavior

I would expect these artefacts to not appear 😅 

## Actual behavior

A strange blur/pixellated spikes appear around the edges of the primary buttons when I hover them. The more I hover, the more prominent they become. They don't disappear until page refresh. Happens on most (but not all) primary buttons as far as I can tell.

## Steps to reproduce the problem

1. Using Google Chrome (version: 119.0.6045.123) and MacOS (version: 14.1 (23B74))
2. Opening my test store https://admin.shopify.com/store/black-black-shirts
3. Go to any page with a primary button (e.g. /products, /orders)
4. Hover mouse over the primary button multiple times and the artefacts appear

## Specifications

- Polaris version number: Production
- Browser: Chrome (version: 119.0.6045.123)
- Device: MacBook Pro M1
- Operating System: MacOS (version: 14.1 (23B74))

### LINKED ISSUE #11191: Simplify primary and default button shadows
Image

In some drastic cases it's causing severe render issues:

https://github.com/Shopify/polaris/issues/11162

Image

### PR DESCRIPTION
**Pull request by sam-b-rose**
Closes [#11191](https://github.com/Shopify/polaris/issues/11191)

Closes #11162

This PR:

- Is a rewrite of all `Button.scss` styles reducing the SCSS from `>1k` lines to `287`
- This also removes a few unnecessary internal DOM elements. Why should button have so many elements 🤷 
- Fixes the bevels for all button variants 👈  the main point of the original issue (thanks @heyjoethomas for the design help!)
- Also fixes the Secondary Actions buttons in the Page component

This greatly reduces the complexity of the Button styles and focuses on readability of the custom property variables.

🎩 with this 🌀[spin url](https://admin.web.button.sam-rose.us.spin.dev/store/shop1)

localhost_6006_iframe html_id=all-components-button--all viewMode=story(iPad Mini)

### CODE REVIEW

**Comment by heyjoethomas** [comment]
Hey @sam-b-rose, can we tweak the box shadow of the default button to the following (pulled this from my inspector) 
`0 -0.0625rem 0 0.0625rem rgba(0, 0, 0, .05) inset, 0 0 0 0.0625rem rgba(0, 0, 0, 0.15) inset, 0 0.03125rem 0 0.09375rem #ffffff inset` 

Makes the bottom edge a bit crisper.

File: polaris-react/src/components/Button/Button.tsx [hunk 1]
```diff
@@ -114,48 +112,46 @@ export function Button({
...
   removeUnderline,
-  size = DEFAULT_SIZE,
-  textAlign,
+  size = 'medium',
+  textAlign = 'center',
   fullWidth,
   dataPrimaryLink,
   tone,
-  variant,
+  variant = 'secondary',
```
Comment (alex-page) [inline polaris-react/src/components/Button/Button.tsx:120]: Could this be a breaking change if a `<Button>` without variant today potentially changes it's appearance? I can't quickly see where the default value for `variant` is or was..

**Review by heyjoethomas — APPROVED** [review]

File: .changeset/tender-pugs-crash.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+'@shopify/polaris': minor
+---
+
+Refactor Button styles and bevel
```
Comment (chloerice) [inline .changeset/tender-pugs-crash.md]:
```suggestion
Refactored `Button` styles and bevel
```

File: polaris-react/src/components/Button/Button.tsx (hunk 1 above)
Comment (sam-b-rose) [reply polaris-react/src/components/Button/Button.tsx:120]: I don't _think_ so. If a Button didn't have a variant prop, it would internally map `undefined` to now be `secondary`. This will then apply the "default" styles that where being applied for `<Button variant={undefined}>` before.

If we don't do it this way, then we have to apply all the secondary styles as the default styles. The reason I didn't do this is so we could avoid having to override every style used to create the `secondary` variant in other variants that don't need certain styles (e.g., `plain` doesn't need a background color)

**Review by alex-page — APPROVED** [review]

**Comment by lgriffee** [comment]
Just dropping this here for my own project documentation purposes. 

| Before | After | 
| -- | -- | 
|BEFORE-capture-1975239a|AFTER-capture-91d5096|

File: polaris-react/src/components/Button/Button.scss [hunk 3]
```diff
@@ -1,1043 +1,286 @@
...
 }
 
-.toneCritical {
-  // stylelint-disable -- Button custom properties
-  --pc-button-color: var(--p-color-bg-fill);
-  --pc-button-text: var(--p-color-text-critical);
-  --pc-button-color-hover: var(--p-color-bg-fill-hover);
-  --pc-button-color-active: var(--p-color-bg-fill-active);
-  --pc-button-color-depressed: var(--p-color-bg-fill-active);
+.toneSuccess:is(.variantPrimary) {
```
Comment (chloerice) [inline polaris-react/src/components/Button/Button.scss]: Unfortunately I don't think we are able to use [`:is`](https://caniuse.com/?search=%3Ais) with our [current minimum browser support](https://github.com/Shopify/web/blob/main/.browserslistrc) 👀

File: polaris-react/src/components/Button/Button.tsx (hunk 1 above)
Comment (chloerice) [reply polaris-react/src/components/Button/Button.tsx:120]: I believe `secondary` is being added as a variant to make the default button styles an explicit `variant`, so it will be the same as a Button with no `variant` set.

File: polaris-react/src/components/Button/Button.scss [hunk 4]
```diff
@@ -1,1043 +1,286 @@
...
-      // stylelint-disable-next-line polaris/conventions/polaris/custom-property-allowed-list -- Button custom property
-      --pc-button-text: var(--p-color-text-disabled);
-    }
-  }
-
-  &.iconOnly {
-    margin: calc(-1 * var(--p-space-100));
-
-    path {
-      fill: var(--p-color-icon-secondary);
```
Comment (chloerice) [inline polaris-react/src/components/Button/Button.scss]: The `iconOnly` `fill` declarations will need to be ported over to the rewritten styles, with this missing they're falling back to `currentColor`:

| Current | Rewrite |
|--------|--------|
| Screenshot 2023-12-07 at 3 27 40 PM | Screenshot 2023-12-07 at 3 24 12 PM |
|Screenshot 2023-12-07 at 3 59 25 PM| Screenshot 2023-12-07 at 3 32 02 PM|
|Screenshot 2023-12-07 at 3 55 57 PM|Screenshot 2023-12-07 at 3 57 03 PM|
|Screenshot 2023-12-07 at 4 02 25 PM|Screenshot 2023-12-07 at 4 02 12 PM|

File: polaris-react/src/components/Button/Button.scss [hunk 5]
```diff
@@ -1,1043 +1,286 @@
...
+  --bg: transparent;
+  --bg_hover: var(--bg);
+  --bg_active: var(--bg);
+  --bg_pressed: var(--bg_active);
+  --bg_disabled: var(--p-color-bg-fill-disabled);
+  --color: inherit;
+  --color_hover: var(--color);
+  --color_active: var(--color);
+  --color_pressed: var(--color_active);
+  --color_disabled: var(--p-color-text-disabled);
```
Comment (chloerice) [inline polaris-react/src/components/Button/Button.scss]: We'll need to update the overrides of the Button `--pc-button-` properties in [`ContextualSaveBar`](https://github.com/Shopify/polaris/blob/2b5ecf8df3dcc07a3a6a75939e6f3b588f710ea1/polaris-react/src/components/Frame/components/ContextualSaveBar/ContextualSaveBar.scss#L84-L93)

| Current | Rewrite |
|--------|--------|
| Screenshot 2023-12-07 at 3 36 22 PM | Screenshot 2023-12-07 at 3 38 10 PM|

**Review by chloerice — DISMISSED** [review]
The `Button` rewrite looks and works amazing @sam-b-rose, the SCSS is so easy to read and reason about now!! 🔥  The only bugs I found while tophatting were in icon only plain/tertiary/monochromePlain buttons and needing to update the Button overrides in `ContextualSaveBar`. Updated the PR description with a working Spinstance.

File: polaris-react/src/components/Button/Button.scss (hunk 3 above)
Comment (alex-page) [reply polaris-react/src/components/Button/Button.scss]: We currently use `:is` ~20 times in Polaris 💔 . I also opened this PR in shopify/web https://github.com/Shopify/web/pull/111914

Comment (chloerice) [reply polaris-react/src/components/Button/Button.scss]: Spongebob Squarepants dancing in celebration with a marching band

**Comment by sam-b-rose** [comment]
@chloerice thanks for the review! I've addressed the icon color and Contextual Save Bar overrides 👍 

@mrcthms I've incorporated your improvements to the tertiary button pressed state. I used the `--p-color-bg-fill-selected` color instead, which is what was in the Figma UI Kit originally, just never implemented. Thanks!

File: polaris-react/src/components/Button/Button.scss [hunk 6]
```diff
@@ -1,1043 +1,317 @@
...
+  --pc-button-box-shadow_pressed: var(--pc-button-box-shadow_active);
+  --pc-button-box-shadow_disabled: var(--pc-button-box-shadow);
+  --pc-button-icon-fill: currentColor;
+  --pc-button-icon-fill_disabled: var(--pc-button-color_disabled);
+  border: none;
+  border-radius: var(--p-border-radius-200);
+  background: var(--pc-button-bg);
+  color: var(--pc-button-color);
+  box-shadow: var(--pc-button-box-shadow);
+  fill: var(--pc-button-icon-fill);
```
Comment (chloerice) [inline polaris-react/src/components/Button/Button.scss]:
```suggestion
```

File: polaris-react/src/components/Button/Button.scss [hunk 7]
```diff
@@ -1,1043 +1,317 @@
...
-  justify-content: center;
-  align-items: center;
-  min-width: 1px;
-  min-height: 1px;
-  transform: translateY(0);
-  // stylelint-disable-next-line polaris/motion/declaration-property-unit-disallowed-list -- set transition
-  transition: transform 75ms cubic-bezier(0.19, 0.91, 0.38, 1);
 
-  @media #{$p-breakpoints-md-up} {
+  @media (--p-breakpoints-md-up) {
```
Comment (chloerice) [inline polaris-react/src/components/Button/Button.scss]:
```suggestion
  
  svg {
    fill: var(--pc-button-icon-fill);
  }

  @media (--p-breakpoints-md-up) {
```

File: polaris-react/src/components/Button/Button.scss [hunk 8]
```diff
@@ -1,1043 +1,317 @@
...
-  justify-content: flex-end;
-  text-align: end;
-
-  .Content {
-    justify-content: flex-end;
-  }
+.Button:disabled,
+.Button[disabled],
+.disabled {
+  background: var(--pc-button-bg_disabled);
```
Comment (chloerice) [inline polaris-react/src/components/Button/Button.scss]:
```suggestion
  --pc-button-icon-fill: var(--pc-button-icon-fill_disabled);
  background: var(--pc-button-bg_disabled);
```

File: polaris-react/src/components/Button/Button.scss [hunk 9]
```diff
@@ -1,1043 +1,317 @@
...
+  color: var(--pc-button-color_disabled);
+  fill: var(--pc-button-icon-fill_disabled);
```
Comment (chloerice) [inline polaris-react/src/components/Button/Button.scss]:
```suggestion
```

File: polaris-react/src/components/Button/Button.scss [hunk 10]
```diff
@@ -1,1043 +1,317 @@
...
-.disabled {
-  cursor: default;
-  pointer-events: none;
-}
-
-.loading {
-  position: relative;
+.sizeLarge {
+  --pc-button-padding-block: var(--p-space-150);
+  --pc-button-padding-inline: var(--p-space-300);;
```
Comment (chloerice) [inline polaris-react/src/components/Button/Button.scss]:
```suggestion
  --pc-button-padding-inline: var(--p-space-300);
```

File: polaris-react/src/components/Button/Button.scss [hunk 11]
```diff
@@ -1,1043 +1,317 @@
...
+.loading {
+  color: transparent;
+}
 
-  .Button.pressed {
-    // stylelint-disable-next-line -- required for styling specificicty
-    clip-path: none !important;
-  }
+// INTERACTION
+.pressable:active:not(.variantTertiary, .variantPlain, .variantMonochromePlain)
```
Comment (chloerice) [inline polaris-react/src/components/Button/Button.scss]:
```suggestion
/* stylelint-disable-next-line selector-max-specificity -- Unchained :not selectors don't compile as intended, see https://github.com/Shopify/polaris/pull/9556) */
.pressable:active:not(.variantTertiary):not(.variantPlain):not(.variantMonochromePlain)
```

File: polaris-react/src/components/Button/Button.scss [hunk 12]
```diff
@@ -1,1043 +1,317 @@
...
-  }
-
-  .Icon:last-child {
-    margin-right: calc(-1 * var(--p-space-100));
-  }
-
-  .Icon:only-child {
-    margin-right: 0;
-  }
+  --pc-button-padding-inline: var(--p-space-100);
```
Comment (chloerice) [inline polaris-react/src/components/Button/Button.scss]: The tertiary and plain icon-only buttons are still black and blue:

| Before ([Chromatic](https://5d559397bae39100201eedc1-tfqrgrlkfi.chromatic.com/?path=/story/all-components-button--all)) ([Spin](https://admin.web.test-button-rewrite.chloe-rice.us.spin.dev/store/shop1/products/8))| After ([Chromatic](https://5d559397bae39100201eedc1-vtvnmjbofa.chromatic.com/?path=/story/all-components-button--all)) ([Spin](https://admin.web.test-revamp-button-fixes.chloe-rice.us.spin.dev/store/shop1/products/6))|
|--------|--------|
| Screenshot 2023-12-11 at 11 04 20 PM |Screenshot 2023-12-11 at 11 09 56 PM|
| Screenshot 2023-12-11 at 11 04 42 PM|Screenshot 2023-12-12 at 12 35 43 AM |
| Screenshot 2023-12-11 at 11 04 03 PM |Screenshot 2023-12-11 at 11 09 44 PM|

```suggestion
  &.variantTertiary,
  &.variantPlain {
    --pc-button-icon-fill: var(--p-color-icon-secondary);

    /* stylelint-disable-next-line -- selector-max-class */
    &.toneCritical {
      --pc-button-icon-fill: var(--p-color-text-critical);
    }
  }
}

/* stylelint-disable selector-max-specificity -- Need the high specificity for icon-only interation states because of how high specificity is with :is usage in the variant and tone class declarations above */
.iconOnly:is(:hover, :focus):not(.variantPrimary):not(.toneCritical.variantTertiary) {
  --pc-button-icon-fill: var(--p-color-icon-hover);
}

.iconOnly:is(:active, .pressed):not(.variantPrimary):not(.toneCritical.variantTertiary) {
  --pc-button-icon-fill: var(--p-color-icon-active);
}
/* stylelint-enable selector-max-specificity */

.disabled:not(.variantPrimary),
.iconOnly.disabled:not(.variantPrimary) {
  --pc-button-icon-fill_disabled: var(--p-color-icon-disabled);
  --pc-button-icon-fill: var(--pc-button-icon-fill_disabled);
}

.iconOnly:is(.sizeSlim, .sizeMedium) {
  --pc-button-padding-inline: var(--p-space-100);
```

**Review by chloerice — CHANGES_REQUESTED** [review]
ContextualSaveBar looks great! Those pesky icon-only buttons still need the correct fill and interaction states. I suggested tophatted fixes and did my best to finesse the CSS needed to fit the new conventions 😅

**Review by mrcthms — APPROVED** [review]
LGTM for the tertiary pressed issue

File: polaris-react/src/components/Button/Button.scss (hunk 11 above)
Comment (sam-b-rose) [reply polaris-react/src/components/Button/Button.scss]: I'm `:not` sure if this is a bug that was fixed, but checking the CSS build output, it appears to be compiling correctly 👍 

```css
/* Looking at polaris/polaris-react/build/esm/styles.css */

.Polaris-Button--pressable:active:not(.Polaris-Button--variantTertiary, .Polaris-Button--variantPlain, .Polaris-Button--variantMonochromePlain) > * { transform: translate3d(0, 0.0625rem, 0); }
```

File: polaris-react/src/components/Button/Button.scss [hunk 13]
```diff
@@ -1,1043 +1,352 @@
...
-    line-height: var(--p-font-line-height-500);
-    letter-spacing: initial;
-
-    @media #{$p-breakpoints-md-up} {
-      line-height: var(--p-font-line-height-400);
-    }
-  }
+.iconOnly:is(.variantTertiary) {
+  --pc-button-icon-fill: var(--p-color-icon-secondary);
+  --pc-button-icon-fill_hover: var(--p-color-icon);
```
Comment (chloerice) [inline polaris-react/src/components/Button/Button.scss]: Should the pressed/active and hover states of tertiary icon only buttons use the `icon-secondary-x` tokens?

```suggestion
  --pc-button-icon-fill_hover: var(--p-color-icon-secondary-hover);
  --pc-button-icon-fill_active: var(--p-color-icon-secondary-active);
```

|| `--p-color-icon-x` | `--p-color-icon-secondary-x` |
|--------|--------|--------|
|(static for comparison)|Screenshot 2023-12-13 at 12 30 12 PM | Screenshot 2023-12-13 at 12 30 12 PM|
|hover| Screenshot 2023-12-13 at 12 24 36 PM | Screenshot 2023-12-13 at 12 25 16 PM |
|pressed/active| Screenshot 2023-12-13 at 12 20 16 PM | Screenshot 2023-12-13 at 12 21 06 PM|

File: polaris-react/src/components/Button/Button.scss [hunk 14]
```diff
@@ -1,1043 +1,352 @@
...
-    font-size: var(--p-font-size-325);
-    font-weight: var(--p-font-weight-medium);
-    line-height: var(--p-font-line-height-500);
-    letter-spacing: initial;
-
-    @media #{$p-breakpoints-md-up} {
-      line-height: var(--p-font-line-height-400);
-    }
-  }
+.iconOnly:is(.variantTertiary) {
```
Comment (chloerice) [inline polaris-react/src/components/Button/Button.scss]: (Icon only plain buttons are secondary too) 

```suggestion
.iconOnly:is(.variantTertiary, .variantPlain) {
```

| Before | After |
|--------|--------|
| Screenshot 2023-12-13 at 12 54 34 PM | Screenshot 2023-12-13 at 12 53 42 PM |

File: polaris-react/src/components/Button/Button.scss (hunk 13 above)
Comment (heyjoethomas) [reply polaris-react/src/components/Button/Button.scss]: Yes. This makes more sense.

File: polaris-react/src/components/Button/Button.scss (hunk 14 above)
Comment (sam-b-rose) [reply polaris-react/src/components/Button/Button.scss]: I did notice this, but it seemed confusing to me why the `plain` icon button wouldn't be blue. Would it make more sense to use the `monochromePlain` or `tertiary`? 🤔 

@heyjoethomas should we continue this pattern or could we consider this a "fix" by retaining the blue link color for iconOnly buttons?

File: polaris-react/src/components/Button/Button.scss [hunk 15]
```diff
@@ -1,1043 +1,352 @@
...
-  }
-
-  &.sizeLarge {
-    margin-block: calc(-1 * var(--p-space-200));
-    margin-inline: calc(-1 * var(--p-space-500));
-  }
-
-  &.iconOnly {
-    margin: 0;
-    padding: 0;
```
Comment (chloerice) [inline polaris-react/src/components/Button/Button.scss]: The `.iconOnly:is(.variantPlain, .variantMonochromePlain)` `margin: 0;` and `padding: 0;` needs to be ported over, without it there's an alignment regression in the plain variant.

| Before | After |
|--------|--------|
|Screenshot 2023-12-13 at 3 29 59 PM |Screenshot 2023-12-13 at 3 34 44 PM|

File: polaris-react/src/components/Button/Button.scss (hunk 14 above)
Comment (sam-b-rose) [reply polaris-react/src/components/Button/Button.scss]: Confirmed with Joe, the less risky route is to keep the color secondary as it is in `main` currently.

I still think this design choice is confusing and we should perhaps revisit the decision in a separate issue 👍

File: polaris-react/src/components/Button/Button.scss (hunk 12 above)
Comment (sam-b-rose) [reply polaris-react/src/components/Button/Button.scss]: Good catch, updated 👍

Comment (chloerice) [reply polaris-react/src/components/Button/Button.scss]: Plain and tertiary are fixed! 🙌🏽 Just still need to override/handle the toneCritical plain and tertiary variants:

Tertiary critical icon only should be filled with `color-text-critical-x` tokens
Screenshot 2023-12-14 at 11 47 41 AM

Plain critical icon only has the right interaction states but needs `color-text-critical` when not being interacted with
Screenshot 2023-12-14 at 11 47 50 AM

**Review by chloerice — APPROVED** [review]
:shipit:

**Comment by aveline** [comment]
I will defer to design on whether this is intentional, but the updated bevel on active state for success and critical looks heavier

Before|After
:----:|:----:
Screenshot 2023-12-15 at 7 58 47 AM|Screenshot 2023-12-15 at 7 59 20 AM

File: polaris-react/src/components/Button/Button.scss (hunk 3 above)
Comment (aaronccasanova) [reply polaris-react/src/components/Button/Button.scss]: Heads up, this is the result on Safari 14 in BrowserStack (wasn't able to load Safari 13). cc @sam-b-rose @chloerice @alex-page

**Before**
Screenshot 2023-12-15 at 8 38 39 AM


**After**
Screenshot 2023-12-15 at 8 29 17 AM

**Review by aveline — APPROVED** [review]
🎉 Nice work!

**Comment by sam-b-rose** [comment]
> the updated bevel on active state for success and critical looks heavier

Great catch! I forgot to apply the success and critical active/pressed box-shadow. Updated, thank you @aveline!

**Comment by Arlen22** [comment]
Ran into a small issue with the new box shadows. https://github.com/Shopify/polaris/issues/11377
