### PR TITLE
Fix overlapping checkbox when sticky header is present

### LINKED ISSUE #9026: [IndexTable] Non-sticky elements appear above sticky elements
## Issue summary

While the sticky header overlaps the non-sticky header, the non-sticky elements are still partially visible.

https://user-images.githubusercontent.com/86790511/233193677-f4d0a6db-363d-4712-b4b6-065847f6716c.mp4

## Expected behavior

Non-sticky header elements do not appear on top of sticky header elements

## Actual behavior

Non-sticky header elements appear on top of sticky header checkbox

## Steps to reproduce the problem

1. Create an IndexTable with a large number of rows, so that you can trigger the sticky header
2. Scroll down just as the sticky header enables and it overlaps the the non-sticky header

## Reduced test case

Reproducible within the "With Bulk Actions and Selection Across Pages" IndexTable story

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 10.43.0
- Browser: Chrome
- Device: MacBook Pro
- Operating System: macOS

### PR DESCRIPTION
**Pull request by sam-b-rose**
### WHY are these changes introduced?

Fixes #9026 

... and _possibly_ #9027 I am still testing, but it seems to have resolved this issue. Though, I think the real issue is that #9027 is just difficult to replicate consistently.

🔗 [Spin link](https://admin.web.sticky-index-table.sam-rose.us.spin.dev/store/shop1/products?selectedView=all)

### WHAT is this pull request doing?

This PR

- fixes overlapping checkbox when sticky header is present
- passes heading alignment props to sticky header

### Screenshots

<details>
<summary>Before</summary>
before
</details>

<details>
<summary>After</summary>
after
</details>

### CODE REVIEW

**Review by alex-page — APPROVED** [review]
Nice win. We will want to tophat this pretty thoroughly.

File: polaris-react/src/components/IndexTable/IndexTable.tsx [hunk 1]
```diff
@@ -1076,10 +1076,13 @@ function IndexTableBase({
       tableHeadingRects.current && tableHeadingRects.current.length > position
         ? {minWidth: tableHeadingRects.current[position].offsetWidth}
         : undefined;
+    const headingAlignment = heading.alignment || 'start';
 
     const headingContent = renderHeadingContent(heading, index);
     const stickyHeadingClassName = classNames(
       styles.TableHeading,
+      headingAlignment === 'center' && styles['TableHeading-align-center'],
+      headingAlignment === 'end' && styles['TableHeading-align-end'],
```
Comment (mattkubej) [inline polaris-react/src/components/IndexTable/IndexTable.tsx:1085]: Are these changes coupled with the overlapping issue or is this addressing a separate issue where alignment was not being set correctly on sticky headers?

File: polaris-react/src/components/IndexTable/IndexTable.scss [hunk 2]
```diff
@@ -225,7 +225,6 @@ $loading-panel-height: 53px;
 
 .TableHeading {
   background: var(--p-color-bg-subdued);
-  z-index: var(--p-z-index-1);
```
Comment (mattkubej) [inline polaris-react/src/components/IndexTable/IndexTable.scss:228]: Do we have an inclination of why this was here in the first place?

**Review by mattkubej — APPROVED** [review]
Thanks for addressing this and makes sense to me!

Unclear why that was introduced in the first place, but maybe it was an oversight?

**Comment by kyledurand** [comment]
Can you post the spin link when it's ready @samrose3

File: polaris-react/src/components/IndexTable/IndexTable.tsx (hunk 1 above)
Comment (sam-b-rose) [reply polaris-react/src/components/IndexTable/IndexTable.tsx:1085]: This is a separate issue. I can split it out into a different PR. It seemed small enough to include here, but happy to open another PR if preferred.

I figured we could include both fixes, document in the changelog, and tophat thoroughly.

Comment (mattkubej) [reply polaris-react/src/components/IndexTable/IndexTable.tsx:1085]: Keeping it here in the same PR and explaining it in the changelog works for me. Just wanted to make sure I was understanding the changes.

**Comment by sam-b-rose** [comment]
@kyledurand

> Can you post the spin link when it's ready

Yep, here you go! Thanks for helping to tophat!

https://admin.web.sticky-index-table.sam-rose.us.spin.dev/store/shop1/products?selectedView=all

**Comment by kyledurand** [comment]
Looks great to me 👍 Solid fixes!

File: polaris-react/src/components/IndexTable/IndexTable.scss (hunk 2 above)
Comment (sam-b-rose) [reply polaris-react/src/components/IndexTable/IndexTable.scss:228]: Looks like it was added to support Tooltips on header content PR #8277 (this [line here](https://github.com/Shopify/polaris/pull/8277/files#diff-e9d0c2a006c030f315115b92e46c3b44667bef0b5e909e1b3af852e6eb2b605bR214)).

I verified that the Tooltips on heading content (sticky and non-sticky header) still work using the Storybook examples "With Sortable Custom Headings" and "With Custom Tooltips" 👍
