### PR TITLE
Fixed ref error and removed bulk action warning

### LINKED ISSUE #11133: [Tabs] Fix invalid ref error and return focus
## Issue summary

When using the tabs component to create new views, there's an error for invalid refs. Because of this focus is also not passed back to the activator when the create view modal is closed.

Screenshot 2023-11-07 at 2 16 45 PM

## Expected behavior

No error

## Actual behavior

Has an error

## Steps to reproduce the problem

* Load a tabs example with the create view action
* You'll have an error in the console

### PR DESCRIPTION
**Pull request by AndrewMusgrave**
### WHY are these changes introduced?

Fixes https://github.com/Shopify/polaris/issues/11133, https://github.com/Shopify/polaris/issues/11134

The pull request address two issues.

`Tooltips` is a functional component that doesn't use `forwardRef`. However, the modal component focuses it's activator for accessibility reasons. The tabs component is providing a modal with a tooltip as it's activator, resulting in the console error.

The second issue is the promoted bulk actions warning. This warning message display when more than 2 promoted bulk actions are used. However, we don't follow this internally, in our component examples, or have supporting documentation for.

#### Old - Bulk Action warning

Screenshot 2023-11-03 at 10 17 42 AM

#### Old - ref error
Screenshot 2023-11-03 at 10 20 32 AM

### How to 🎩

View a story with over 2 bulk actions. For example `all-components-indextable--with-multiple-promoted-bulk-actions`. The warning should be gone.

View a story with the add view action. For example `all-components-indexfilters--default`. The error should be gone.

### 🎩 checklist

- [ ] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [ ] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [ ] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [ ] Updated the component's `README.md` with documentation changes
- [ ] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

### CODE REVIEW

File: polaris-react/src/components/Tabs/Tabs.tsx [hunk 1]
```diff
@@ -603,13 +603,17 @@ export const Tabs = ({
...
                       newTab
                     ) : (
-                      <Tooltip
-                        content={i18n.translate('Polaris.Tabs.newViewTooltip')}
-                        preferredPosition="above"
-                        hoverDelay={400}
-                      >
-                        {newTab}
-                      </Tooltip>
+                      <div>
```
Comment (dleroux) [inline polaris-react/src/components/Tabs/Tabs.tsx:606]: This is preventing the error but it look a like focus on the tablist is list completely based on 
https://storybook.polaris.shopify.com/?path=/story/all-components-tabs--with-actions
 Better than and error but tabs with action appear to have additional issues

**Review by dleroux — APPROVED** [review]
left a comment but it's probably something outside this PR

File: polaris-react/src/components/Tabs/Tabs.tsx (hunk 1 above)
Comment (AndrewMusgrave) [reply polaris-react/src/components/Tabs/Tabs.tsx:606]: 100 percent! This remove the errors and achieves parody. The next step is determining if tooltip should forwardRef its ref. Which _could_ be a breaking change 😢

**Review by chloerice — APPROVED** [review]
Thank you Andrew!! 🙏🏽

File: polaris-react/src/components/Tabs/Tabs.tsx (hunk 1 above)
Comment (AndrewMusgrave) [reply polaris-react/src/components/Tabs/Tabs.tsx:606]: I may have misunderstood the original comment. The should fix the focus issue as well, since modal finds the first focusable element. What error are you seeing in tabs?

Comment (dleroux) [reply polaris-react/src/components/Tabs/Tabs.tsx:606]: I'm thinking the focus should go back the activator, the tooltip in this case, but not in this PR.

Comment (AndrewMusgrave) [reply polaris-react/src/components/Tabs/Tabs.tsx:606]: Perfect! This PR fixes that 😄 

https://github.com/Shopify/polaris/assets/24610840/c5899eec-7ddf-42a2-b789-f1fbecd81460
