### PR TITLE
[Button] Fix `buttonFrom` not mapping `ComplexAction` boolean properties to `variant` and `tone`

### LINKED ISSUE #10995: [PageActions] Action props do not match button props
## Issue summary

Defining a page action with `destructive: true` does not changes the visual style of the button.

16-17-vlfd0-d97n7

Edit: Apparently the contract for an action still accept a lot of deprecated button props like destructive, outline and plain ([see types](https://github.com/Shopify/polaris/blob/main/polaris-react/src/types.ts#L159)) that are lost in the [buttonFrom](https://github.com/Shopify/polaris/blob/main/polaris-react/src/components/Button/utils.tsx#L28C4-L28C4) util

## Expected behavior

Actions (both primary and secondary) that are `destructive: true` should show a button with `tone="critical"` and an appropiate variant or primary value depending on other props.
Actions with `plain: true` should show a button with `variant="plain"`

## Actual behavior

There is no way to make an action look "destructive" or customize its appearance, since tone and variant are not acceptable props. The only workaround is to pass a react component instead of an action.

## Reduced test case

https://codesandbox.io/s/sleepy-dhawan-h9nt2n?file=/App.tsx

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 12

### LINKED ISSUE #11006: Modal primaryAction with prop destructive not work
## Issue summary
I use Modal component with primaryAction prop. i want the button become red color but it color is primary color

image
image

## Expected behavior
image

### PR DESCRIPTION
**Pull request by chloerice**
### WHY are these changes introduced?

Fixes https://github.com/Shopify/polaris/issues/10995
Fixes https://github.com/Shopify/polaris/issues/11006

### WHAT is this pull request doing?

Fixes the `buttonFrom` util not mapping the action parameter's boolean variant properties to `variant` and `tone`.

| Before | [After]() |
|--------|--------|
| Screenshot 2023-10-25 at 4 03 52 PM| Screenshot 2023-10-25 at 4 02 41 PM|

### 🎩 checklist

- [ ] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [x] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [ ] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [x] Updated the component's `README.md` with documentation changes
- [x] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

### CODE REVIEW

File: polaris-react/src/components/Button/utils.tsx [hunk 1]
```diff
@@ -26,12 +26,22 @@ export function buttonsFrom(
 }
 
 export function buttonFrom(
-  {content, onAction, ...action}: ComplexAction,
+  {content, onAction, plain, destructive, ...action}: ComplexAction,
   overrides?: Partial<ButtonProps>,
   key?: any,
 ) {
+  const variant = !overrides?.variant && plain ? 'plain' : overrides?.variant;
+  const tone = !overrides?.tone && destructive ? 'critical' : overrides?.tone;
```
Comment (chloerice) [inline polaris-react/src/components/Button/utils.tsx:34]: @kyledurand ^

Comment (kyledurand) [reply polaris-react/src/components/Button/utils.tsx:34]: Does this still cause TS errors though?

**Review by kyledurand — APPROVED** [review]

File: polaris-react/src/components/Button/utils.tsx (hunk 1 above)
Comment (chloerice) [reply polaris-react/src/components/Button/utils.tsx:34]: No, because the Button gets the correct props set. The `buttonFrom` API doesn't need to change, the bug where variant and tone weren't set when the action was configured with properties that should map variant and tone is all that needed to be fixed. So any `Action`ish typed objects implemented in Polaris and Web can remain as they're typed and the buttons will be correct with this patch.

Comment (kyledurand) [reply polaris-react/src/components/Button/utils.tsx:34]: Makes sense! We'll still need to, at some point, allow these actions to set tone and variant I think but this is a solid fix for now. That global types file is 🤯

Comment (chloerice) [reply polaris-react/src/components/Button/utils.tsx:34]: I'll creat an issue for deprecating the old booleans on the Action types and adding tone and variant support so we can remove the old boolean properties in v13 💯

File: polaris-react/src/components/Checkbox/Checkbox.scss [hunk 2]
```diff
@@ -80,8 +80,7 @@
       // We set the border-color to transparent here
       // in order for the background color to bleed all the way to the edge of the element.
       border-color: transparent;
-      // stylelint-disable-next-line polaris/color/function-disallowed-list -- set background color
-      background-color: rgba(0, 0, 0, 0.08);
+      background-color: var(--p-color-checkbox-bg-surface-disabled);
```
Comment (chloerice) [inline polaris-react/src/components/Checkbox/Checkbox.scss:83]: (This token has the equivalent value of `rgba(0, 0, 0, 0.08)`)
