### PR TITLE
[IndexTable] Recalculate column widths when the sticky header is rendered

### LINKED ISSUE #9027: [IndexTable] Inconsistent styling between sticky row and non-sticky row
## Issue summary

The sticky row of the Index Table does not match the non-sticky row of the Index Table.

Within Admin, this appears to only occur on initial render of the Index Table, but if you navigate away and come back to the page, then the issue no longer exists.

https://user-images.githubusercontent.com/86790511/233195283-2681dbda-156d-423e-baeb-1b31bfb5cd1f.mp4

## Expected behavior

Sticky row matches the styling of the non-sticky row

## Actual behavior

Differing widths and alignment of column headers

## Steps to reproduce the problem

1. Create an IndexTable with a large number of rows, so that you can trigger the sticky header
2. Scroll down just as the sticky header enables and it overlaps the the non-sticky header

## Reduced test case

Reproducible within the "With Bulk Actions and Selection Across Pages" IndexTable story

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 10.43.0
- Browser: Chrome
- Device: MacBook Pro
- Operating System: macOS

### PR DESCRIPTION
**Pull request by sam-b-rose**
Closes #9027 

- Recalculate column widths when the sticky header is rendered
- Update Storybook toolbar config

🔗 Spin link: https://admin.web.sticky-cols.sam-rose.us.spin.dev/store/shop1/products?selectedView=all

### CODE REVIEW

File: polaris-react/src/components/IndexTable/IndexTable.tsx [hunk 1]
```diff
@@ -455,6 +465,7 @@ function IndexTableBase({
     resizeTableHeadings,
     firstStickyHeaderElement,
     tableInitialized,
+    stickyHeaderInitialized,
```
Comment (mattkubej) [inline polaris-react/src/components/IndexTable/IndexTable.tsx]: Is the appropriate formatting of the sticky header dependent on this `useEffect` firing, which is why we encountered the issue on initial render as the sticky header element was not mounted yet? However, why would this work when navigating away and coming back, which would still be a remount?

Without fully understanding this logic, it does seem like this pattern existed for `tableInitialized` and maybe this was a miss with the sticky header?

**Comment by mattkubej** [comment]
This does seem to fix the issue. Thanks!

Would you mind sharing an explanation of your findings and your proposed solution? I think I likely see what's going on, but would like to confirm my understanding when you have a chance.

**Comment by sam-b-rose** [comment]
> Would you mind sharing an explanation of your findings and your proposed solution?

I was hoping that by waiting for the sticky header ref, we could resize the columns after initialization. However, I am still getting occasionally getting the issue. Seems to be a very inconsistent race condition.

I tried removing some of the resizing logic that was specific to the first column when selectable. However, that seems to break things.

**Comment by mattkubej** [comment]
> > Would you mind sharing an explanation of your findings and your proposed solution?
> 
> I was hoping that by waiting for the sticky header ref, we could resize the columns after initialization. However, I am still getting occasionally getting the issue. Seems to be a very inconsistent race condition.
> 
> I tried removing some of the resizing logic that was specific to the first column when selectable. However, that seems to break things.

I'll be a little pressed for time this week, but if you want another set of eyes to look into it or to talk it over, then let me know.

File: polaris-react/src/components/IndexTable/IndexTable.tsx [hunk 2]
```diff
@@ -440,7 +451,7 @@ function IndexTableBase({
     scrollingContainer.current = false;
   }, []);
 
-  useEffect(() => {
+  useIsomorphicLayoutEffect(() => {
```
Comment (sam-b-rose) [inline polaris-react/src/components/IndexTable/IndexTable.tsx:444]: I believe by changing this to an `useIsomorphicLayoutEffect`, this will run after the initial paint and thus be able to run the `resizeTableHeadings` with the proper widths.

@kyledurand @mattkubej can you 🎩 this fix? The spin link should be updated with the latest snapshot and changes.

Comment (mattkubej) [reply polaris-react/src/components/IndexTable/IndexTable.tsx:444]: Oh nice find! This does seem to fix it

Comment (kyledurand) [reply polaris-react/src/components/IndexTable/IndexTable.tsx:444]: This makes sense. I had to do the same thing for page actions that did some measuring after web shipped react 18

File: polaris-react/src/components/IndexTable/IndexTable.tsx (hunk 1 above)
Comment (kyledurand) [reply polaris-react/src/components/IndexTable/IndexTable.tsx]: Is this ref / useCallback still necessary?

Comment (sam-b-rose) [reply polaris-react/src/components/IndexTable/IndexTable.tsx]: Good point. Adding just that didn't seem to fix the issue, so likely no. Will remove and retest 👍

Comment (sam-b-rose) [reply polaris-react/src/components/IndexTable/IndexTable.tsx]: I was able to clean this up, leaving only the `useIsomorphicLayoutEffect`, which fixes the issue. Nice call, @kyledurand 💯

**Review by kyledurand — APPROVED** [review]
I wonder if `useIsAfterInitialMount` should be changed from using `useEffect` to `useIsomorphicLayoutEffect`. Should be a follow up anyway. This looks great

File: .changeset/four-birds-deliver.md [hunk 3]
```diff
@@ -0,0 +1,5 @@
+---
+'@shopify/polaris': patch
+---
+
+Recalculated IndexTable column widths when the sticky header is rendered.
```
Comment (sam-b-rose) [inline .changeset/four-birds-deliver.md]:
```suggestion
Recalculated IndexTable sticky header column widths inside of a `useIsomorphicLayoutEffect` after the table is updated.
```
