### PR TITLE
[DataTable] Fix dom validation error, focus states and icon shimmering.

### LINKED ISSUE #6585: DataTable contains invalid markup
## Issue summary

A bug was introduced in #5539 where a `<div>` component can be inserted directly under a `<table>` component for DataTable's.

image

https://github.com/Shopify/polaris/blob/main/polaris-react/src/components/DataTable/DataTable.tsx#L313

## Expected behavior
Any markup produced by Polaris should be valid HTML. 

## Actual behavior
Invalid markup is produced.

## Steps to reproduce the problem

Create any DataTable with a `stickyHeader`

## Reduced test case

The styles aren't setup correctly, but the issue is reproduced:
https://codesandbox.io/s/shopify-polaris-react-typescript-playground-forked-cljedh?file=/src/index.tsx

If you inspect the markup you will see the incorrect `<div>`

image

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: latest (9.19.0)
- Browser: Chrome
- Device: Desktop
- Operating System: Mac

### PR DESCRIPTION
**Pull request by philschoefer**
### WHY are these changes introduced?

Resolves https://github.com/Shopify/polaris/issues/6585

- Updates `DataTable` to fix console warning about improperly nested HTML.
- Updates `DataTable` to fix shimmering icon hover state.
- Updates `DataTable` to ensure focus states remain on the same header element when switching between sticky and regular header when using `fixedFirstColumn`
- Improves `DataTable` tooltip when using `truncate` prop.

Related: https://github.com/Shopify/core-issues/issues/40678, https://github.com/Shopify/core-issues/issues/40809

#### Fix shimmering icon

<details>
      <summary>Before and After Video</summary>
      
##### Before

https://user-images.githubusercontent.com/4960217/178086283-e2931baa-dc11-4010-8f99-1854c7e17415.mp4

##### After

https://user-images.githubusercontent.com/4960217/178085907-79861323-368a-4b2b-8cfa-999a12607d73.mp4

</details>

#### Keep hover state on sticky header with fixed first column

<details>
      <summary>Before and After Video</summary>
      
##### Before

https://user-images.githubusercontent.com/4960217/178086264-911589d7-6c7f-4011-b0b9-fafab3878098.mp4

##### After

https://user-images.githubusercontent.com/4960217/178085950-4526c854-4174-4cb7-ba0f-5b7f84825e14.mp4

</details>

#### Ensuring tooltips on overflow won't contain any `<a>` tags when using `Link` component.

<details>
      <summary>Before and After Video</summary>
      
##### Before

https://user-images.githubusercontent.com/4960217/178086212-fb62f403-8e6b-4225-8f90-95308e221549.mp4

##### After

https://user-images.githubusercontent.com/4960217/178085989-e2477f77-7c59-4635-8cb8-e87118aa9a03.mp4

</details>

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris/blob/main/README.md#local-development)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris/blob/main/.github/CONTRIBUTING.md#changelog)

<details>
<summary>Copy-paste this code in <code>playground/Playground.tsx</code>:</summary>

```jsx
import React, {useState, useCallback} from 'react';

import {Card, Link, Page, DataTable} from '../src';

function FullDataTableExample() {
  const [sortedRows, setSortedRows] = useState(null);

  const initiallySortedRows = [
    [
      <Link
        removeUnderline
        url="https://www.example.com"
        key="emerald-silk-gown"
      >
        Emerald Silk Gown
      </Link>,
      '$875.00',
      124689,
      140,
      '$121,500.00',
      124689,
      140,
      '$121,500.00',
    ],
    [
      <Link
        removeUnderline
        url="https://www.example.com"
        key="mauve-cashmere-scarf"
      >
        Mauve Cashmere Scarf
      </Link>,
      '$230.00',
      124533,
      83,
      '$19,090.00',
      124689,
      140,
      '$121,500.00',
    ],
    [
      <Link
        removeUnderline
        url="https://www.example.com"
        key="navy-merino-wool"
      >
        Navy Merino Wool Blazer with khaki chinos and yellow belt
      </Link>,
      '$445.00',
      124518,
      32,
      '$14,240.00',
      124689,
      140,
      '$121,500.00',
    ],
    [
      <Link
        removeUnderline
        url="https://www.example.com"
        key="emerald-silk-gown"
      >
        Emerald Silk Gown
      </Link>,
      '$875.00',
      124689,
      140,
      '$121,500.00',
      124689,
      140,
      '$121,500.00',
    ],
    [
      <Link
        removeUnderline
        url="https://www.example.com"
        key="mauve-cashmere-scarf"
      >
        Mauve Cashmere Scarf
      </Link>,
      '$230.00',
      124533,
      83,
      '$19,090.00',
      124689,
      140,
      '$121,500.00',
    ],
    [
      <Link
        removeUnderline
        url="https://www.example.com"
        key="navy-merino-wool"
      >
        Navy Merino Wool Blazer with khaki chinos and yellow belt
      </Link>,
      '$445.00',
      124518,
      32,
      '$14,240.00',
      124689,
      140,
      '$121,500.00',
    ],
    [
      <Link
        removeUnderline
        url="https://www.example.com"
        key="emerald-silk-gown"
      >
        Emerald Silk Gown
      </Link>,
      '$875.00',
      124689,
      140,
      '$121,500.00',
      124689,
      140,
      '$121,500.00',
    ],
    [
      <Link
        removeUnderline
        url="https://www.example.com"
        key="mauve-cashmere-scarf"
      >
        Mauve Cashmere Scarf
      </Link>,
      '$230.00',
      124533,
      83,
      '$19,090.00',
      124689,
      140,
      '$121,500.00',
    ],
    [
      <Link
        removeUnderline
        url="https://www.example.com"
        key="navy-merino-wool"
      >
        Navy Merino Wool Blazer with khaki chinos and yellow belt
      </Link>,
      '$445.00',
      124518,
      32,
      '$14,240.00',
      124689,
      140,
      '$121,500.00',
    ],
    [
      <Link
        removeUnderline
        url="https://www.example.com"
        key="emerald-silk-gown"
      >
        Emerald Silk Gown
      </Link>,
      '$875.00',
      124689,
      140,
      '$121,500.00',
      124689,
      140,
      '$121,500.00',
    ],
    [
      <Link
        removeUnderline
        url="https://www.example.com"
        key="mauve-cashmere-scarf"
      >
        Mauve Cashmere Scarf
      </Link>,
      '$230.00',
      124533,
      83,
      '$19,090.00',
      124689,
      140,
      '$121,500.00',
    ],
    [
      <Link
        removeUnderline
        url="https://www.example.com"
        key="navy-merino-wool"
      >
        Navy Merino Wool Blazer with khaki chinos and yellow belt
      </Link>,
      '$445.00',
      124518,
      32,
      '$14,240.00',
      124689,
      140,
      '$121,500.00',
    ],
    [
      <Link
        removeUnderline
        url="https://www.example.com"
        key="emerald-silk-gown"
      >
        Emerald Silk Gown
      </Link>,
      '$875.00',
      124689,
      140,
      '$121,500.00',
      124689,
      140,
      '$121,500.00',
    ],
    [
      <Link
        removeUnderline
        url="https://www.example.com"
        key="mauve-cashmere-scarf"
      >
        Mauve Cashmere Scarf
      </Link>,
      '$230.00',
      124533,
      83,
      '$19,090.00',
      124689,
      140,
      '$121,500.00',
    ],
    [
      <Link
        removeUnderline
        url="https://www.example.com"
        key="navy-merino-wool"
      >
        Navy Merino Wool Blazer with khaki chinos and yellow belt
      </Link>,
      '$445.00',
      124518,
      32,
      '$14,240.00',
      124689,
      140,
      '$121,500.00',
    ],
    [
      <Link
        removeUnderline
        url="https://www.example.com"
        key="emerald-silk-gown"
      >
        Emerald Silk Gown
      </Link>,
      '$875.00',
      124689,
      140,
      '$121,500.00',
      124689,
      140,
      '$121,500.00',
    ],
    [
      <Link
        removeUnderline
        url="https://www.example.com"
        key="mauve-cashmere-scarf"
      >
        Mauve Cashmere Scarf
      </Link>,
      '$230.00',
      124533,
      83,
      '$19,090.00',
      124689,
      140,
      '$121,500.00',
    ],
    [
      <Link
        removeUnderline
        url="https://www.example.com"
        key="navy-merino-wool"
      >
        Navy Merino Wool Blazer with khaki chinos and yellow belt
      </Link>,
      '$445.00',
      124518,
      32,
      '$14,240.00',
      124689,
      140,
      '$121,500.00',
    ],
  ];

  const rows = sortedRows ? sortedRows : initiallySortedRows;
  const handleSort = useCallback(
    (index, direction) => setSortedRows(sortCurrency(rows, index, direction)),
    [rows],
  );

  return (
    <Page title="Sales by product">
      <Card>
        <DataTable
          columnContentTypes={[
            'text',
            'numeric',
            'numeric',
            'numeric',
            'numeric',
            'numeric',
            'numeric',
            'numeric',
            'numeric',
            'numeric',
            'numeric',
          ]}
          headings={[
            'Product',
            'Price',
            'SKU Number',
            'Net quantity',
            'Net sales',
            'SKU Number',
            'Net quantity',
            'Net sales',
          ]}
          rows={rows}
          totals={['', '', '', 255, '$155,830.00', '', 255, '$155,830.00']}
          sortable={[true, true, false, false, true]}
          defaultSortDirection="descending"
          initialSortColumnIndex={4}
          onSort={handleSort}
          // footerContent={`Showing ${rows.length} of ${rows.length} results`}
          stickyHeader
          hasFixedFirstColumn
          truncate
        />
      </Card>
    </Page>
  );

  function sortCurrency(rows, index, direction) {
    return [...rows].sort((rowA, rowB) => {
      const amountA = parseFloat(rowA[index].substring(1));
      const amountB = parseFloat(rowB[index].substring(1));

      return direction === 'descending' ? amountB - amountA : amountA - amountB;
    });
  }
}

export function Playground() {
  return <FullDataTableExample />;
}
```

</details>

### 🎩 checklist

- [x] Tested on [mobile](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting.md#cross-browser-testing)
- [x] Tested on [multiple browsers](https://help.shopify.com/en/manual/shopify-admin/supported-browsers)
- [x] Tested for [accessibility](https://github.com/Shopify/polaris/blob/main/documentation/Accessibility%20testing.md)
- [x] Updated the component's `README.md` with documentation changes
- [ ] [Tophatted documentation](https://github.com/Shopify/polaris/blob/main/documentation/Tophatting%20documentation.md) changes in the style guide

### CODE REVIEW

**Review by ErickTamayo — APPROVED** [review]
LGTM

**Comment by blboyle** [comment]
https://screenshot.click/12-06-xm8k6-4eol8.mp4

@philschoefer @JeremyLudwigDev 

The headings move back and forth from sticky to non-sticky, but the navigation ones do not.

**Comment by blboyle** [comment]
https://screenshot.click/12-39-zu9v4-wu9n4.mp4

This is what it looks like for keyboard focusing when you combine the fixed first column and header.

I do not know if this is a blocker or not, but the tabbing does not stay on the on link if you have both. Near the end of the above screen recording.

**Review by blboyle — APPROVED** [review]

**Comment by blboyle** [comment]
There are a few things that could be cleaned up in followup (as per our chat regarding the first column) but this looks great to get out in order to fix that error. 👍🏻

**Review by blboyle — APPROVED** [review]

File: polaris-react/src/components/DataTable/DataTable.tsx [hunk 1]
```diff
@@ -260,16 +262,24 @@ class DataTableInner extends PureComponent<CombinedProps, DataTableState> {
...
-      <Navigation
-        columnVisibilityData={columnVisibilityData}
-        isScrolledFarthestLeft={isScrolledFarthestLeft}
-        isScrolledFarthestRight={isScrolledFarthestRight}
-        navigateTableLeft={this.navigateTable('left')}
-        navigateTableRight={this.navigateTable('right')}
-        fixedFirstColumn={fixedFirstColumn}
-      />
-    );
+    const navigationMarkup = (location: 'sticky' | 'header') =>
```
Comment (ErickTamayo) [inline polaris-react/src/components/DataTable/DataTable.tsx:265]: I think this can be wrapped into a `useCallback` and wrap both calls inside a `useMemo`


```js
const stickyMarkup = useMemo(() => navigationMarkup('sticky'), [navigationMarkup])
const headerMarkup = useMemo(() => navigationMarkup('header'), [navigationMarkup])
```

File: polaris-react/src/components/DataTable/DataTable.tsx [hunk 2]
```diff
@@ -260,16 +262,24 @@ class DataTableInner extends PureComponent<CombinedProps, DataTableState> {
...
+            if (location === 'header') {
+              this.headerNav = ref;
+            } else if (location === 'sticky') {
+              this.stickyNav = ref;
+            }
+          }}
+        />
+      );
 
     const stickyHeaderMarkup = stickyHeader ? (
```
Comment (ErickTamayo) [inline polaris-react/src/components/DataTable/DataTable.tsx:284]: This should be wrapped inside a `useMemo`

**Review by ErickTamayo — CHANGES_REQUESTED** [review]

File: polaris-react/src/components/DataTable/DataTable.tsx (hunk 1 above)
Comment (JeremyLudwigDev) [reply polaris-react/src/components/DataTable/DataTable.tsx:265]: This won't work since we can't use hooks in a class component.

**Review by ErickTamayo — APPROVED** [review]
