### PR TITLE
[Listbox.Action] Fix rendering of the action when used outside an Autocomplete

### LINKED ISSUE #4884: [Combobox][Listbox]When using allowMultiple for Combobox, Listbox action has a Checkbox on it
## Issue summary
This scenario is when using custom Listbox options as content of a Combobox. 
When using `allowMultiple` for the Combobox, the rendered Listbox action has a Checkbox on it but it should not.

## Expected behavior

The provided Listbox action should not have a checkbox as its not a 'option' to be selected. 

## Actual behavior

image

## Steps to reproduce the problem

Open up the combo box in the CodeSandbox provided below. It show the usage of a Listbox inside a Combobox with `allowMultiple` set to trus.

## Reduced test case

https://codesandbox.io/s/shopify-polaris-react-typescript-playground-forked-z9nqe

## Specifications

- Are you using the React components? (Y/N): Y
- Polaris version number: 7.5.0
- Browser: Any
- Device:
- Operating System:

Or run `npx envinfo --system --binaries --browsers --npmPackages react,react-dom,@shopify/polaris` to provide specifications on your environment including version numbers, browser, device, and operating system.

Paste the results here:

```bash

```

### PR DESCRIPTION
**Pull request by dleroux**
### WHY are these changes introduced?

Fixes https://github.com/Shopify/polaris-react/issues/4884

The Autocomplete context was providing the Listbox.Action with the boolean context identifying the Action as an Action which was responsible for the CSS. In the issue reported the Action was being used inside a Comboxbox as oppose to Autocomplete therefor the context was missing.

### WHAT is this pull request doing?

I moved the context to the Listbox.Action. I also fixed a few styling issues. 

https://user-images.githubusercontent.com/1229901/149540299-cbb96d49-e56a-4724-843b-41f7fc35b9dc.mov

Screen Shot 2022-01-14 at 9 30 00 AM

https://user-images.githubusercontent.com/1229901/149540307-a4e028fd-4443-4475-b18a-d053543d1733.mov

**before:**
Screen Shot 2022-01-14 at 1 02 58 PM

**after:**
Screen Shot 2022-01-14 at 1 03 15 PM

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris-react/blob/master/README.md#development)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris-react/blob/master/documentation/Versioning%20and%20changelog.md)

<details>
<summary>Copy-paste this code in <code>playground/Playground.tsx</code>:</summary>

```jsx
import React from 'react';
import {CirclePlusMinor, SearchMinor} from '@shopify/polaris-icons';

import {Page, Combobox, Listbox, Icon} from '../src';

export function Playground() {
  const listAction = (
    <Listbox.Action icon={CirclePlusMinor} value="testAction" divider>
      Test action
    </Listbox.Action>
  );

  const listOptions = (
    <>
      <Listbox.Option key="1" value="1">
        My first option
      </Listbox.Option>
      <Listbox.Option key="2" value="2">
        My second option
      </Listbox.Option>
    </>
  );

  const listBox = (
    <Listbox onSelect={() => {}}>
      {listAction}
      {listOptions}
    </Listbox>
  );
  return (
    <Page title="Playground">
      <Combobox
        allowMultiple
        activator={
          <Combobox.TextField
            autoComplete="off"
            prefix={<Icon source={SearchMinor} color="base" />}
            label="search"
            labelHidden
            onChange={() => {}}
          />
        }
      >
        {listBox}
      </Combobox>
    </Page>
  );
}
```

</details>

### 🎩 checklist

- [ ] Tested on [mobile](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md#cross-browser-testing)
- [ ] Tested on [multiple browsers](https://help.shopify.com/en/manual/intro-to-shopify/shopify-admin/supported-browsers)
- [ ] Tested for [accessibility](https://github.com/Shopify/polaris-react/blob/master/documentation/Accessibility%20testing.md)
- [x] Updated the component's `README.md` with documentation changes
- [x] [Tophatted documentation](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting%20documentation.md) changes in the style guide
- [ ] For visual design changes, ping @ sarahill to update the Polaris UI kit

### CODE REVIEW

File: src/components/Autocomplete/components/MappedAction/MappedAction.tsx [hunk 1]
```diff
@@ -86,7 +86,6 @@ export function MappedAction({
       external,
       onAction,
       destructive,
-      isAction: true,
```
Comment (dleroux) [inline src/components/Autocomplete/components/MappedAction/MappedAction.tsx:89]: Moved this out since onAction is sufficient to know its an action

File: src/components/Listbox/components/Action/Action.scss [hunk 2]
```diff
@@ -5,6 +5,10 @@
   flex: 1;
 }
 
+.ActionDivider {
+  margin-bottom: spacing(extra-tight);
```
Comment (dleroux) [inline src/components/Listbox/components/Action/Action.scss:9]: Prevents the focus ring from touching the divider

File: src/components/Listbox/components/Action/Action.tsx [hunk 3]
```diff
@@ -4,6 +4,8 @@ import {Icon} from '../../../Icon';
 import type {IconProps} from '../../../Icon';
 import {Option, OptionProps} from '../Option';
 import {TextOption} from '../TextOption';
+import {classNames} from '../../../../utilities/css';
+import {ActionContext} from '../../../../utilities/listbox/context';
```
Comment (dleroux) [inline src/components/Listbox/components/Action/Action.tsx:8]: This content is what identifies the action now

**Review by rox163 — APPROVED** [review]
🎩  and it lgtm! I tried out the Autocomplete as well on this branch and it looks good.

**Review by melnikov-s — APPROVED** [review]
