### PR TITLE
[TextField] Add rows to textarea on initial render

### LINKED ISSUE #4806: Popover miscalculates height when using a multiline TextField
## Issue summary

A Popover will explicitly set the `height` on the overlay, which is calculated based on the contents of the Popover. However, when the contents of the Popover include a TextField component, which has a numerical `multiline` prop, the height of the Popover gets calculated and set incorrectly.

## Expected behavior

The Popover should correctly calculate the height of the contents.

## Actual behavior

It calculates it incorrectly – it uses the default height value of the TextField.

## Steps to reproduce the problem

1. Create a Popover with a multiline Textfield in its contents
2. Observe the Popover being cut off.

## Reduced test case

https://codesandbox.io/s/optimistic-water-4fgqj?file=/App.js

## Specifications

- Are you using the React components? (Y):
- Polaris version number: 7.2.0
- Browser: Chrome
- Device: MacBook
- Operating System: OSX

### PR DESCRIPTION
**Pull request by mattzaitley**
### WHY are these changes introduced?

Fixes #4806 

The way resizing on initial render was working within the `TextField` wasn't resulting in the `PositionedOverlay` recalculating its height

### WHAT is this pull request doing?

Sets the `rows` attribute of the `textarea` if the prop `multiline` has a value, which will ensure the `TextField` component is the proper height on initial render

## 

### How to 🎩

🖥 [Local development instructions](https://github.com/Shopify/polaris-react/blob/master/README.md#development)
🗒 [General tophatting guidelines](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md)
📄 [Changelog guidelines](https://github.com/Shopify/polaris-react/blob/master/documentation/Versioning%20and%20changelog.md)

Open within the playground, and observe that when opening a popup with a textarea 

<details>
<summary>Copy-paste this code in <code>playground/Playground.tsx</code>:</summary>

```jsx
import React, {useState, useCallback} from 'react';

import {Page, Button, FormLayout, Popover, Select, TextField} from '../src';

export function Playground() {
  const [popoverActive, setPopoverActive] = useState(true);
  const [tagValue, setTagValue] = useState('');

  const togglePopoverActive = useCallback(
    () => setPopoverActive((popoverActive) => !popoverActive),
    [],
  );

  const handleTagValueChange = useCallback((value) => setTagValue(value), []);

  const activator = (
    <Button onClick={togglePopoverActive} disclosure>
      Filter
    </Button>
  );
  return (
    <Page title="Playground">
      <div style={{height: '280px'}}>
        <Popover
          active={popoverActive}
          activator={activator}
          onClose={togglePopoverActive}
          ariaHaspopup={false}
          fluidContent
          sectioned
        >
          <FormLayout>
            <TextField
              label="Tags"
              value={tagValue}
              onChange={handleTagValueChange}
              autoComplete="off"
              multiline={5}
            />
            <Button size="slim">Add filter</Button>
          </FormLayout>
        </Popover>
      </div>
    </Page>
  );
}
```

</details>

### 🎩 checklist

- [ ] Tested on [mobile](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting.md#cross-browser-testing)
- [x] Tested on [multiple browsers](https://help.shopify.com/en/manual/intro-to-shopify/shopify-admin/supported-browsers)
- [x] Tested for [accessibility](https://github.com/Shopify/polaris-react/blob/master/documentation/Accessibility%20testing.md)
- [ ] Updated the component's `README.md` with documentation changes
- [ ] [Tophatted documentation](https://github.com/Shopify/polaris-react/blob/master/documentation/Tophatting%20documentation.md) changes in the style guide
- [ ] For visual design changes, ping @ sarahill to update the Polaris UI kit

### CODE REVIEW

**Comment by ghost** [comment]
👋 Thanks for opening your first pull request. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md).

File: src/components/TextField/TextField.tsx [hunk 1]
```diff
@@ -432,6 +432,7 @@ export function TextField({
     pattern,
     inputMode,
     type: inputType,
+    rows: multiline ? multiline : undefined,
```
Comment (BPScott) [inline src/components/TextField/TextField.tsx]: multiline can be a boolean according to the props. Is passing a boolean to a textarea's rows attribute valid?

Comment (dleroux) [reply src/components/TextField/TextField.tsx]: I'm guessing we can probably make this 1 as a default when multiline as this is what it renders as when true

**Review by dleroux — APPROVED** [review]
Sorry I missed the update on this. There's conflicts but I think this will work.
